class StackBuilder
  DATA_DIRECTORIES = %w[postgresql redis influxdb].freeze

  HELIOS_MARKER = 'Generated by Helios'.freeze

  SECRET_DEFAULTS = {
    'postgres_password' => -> { SecureRandom.alphanumeric(32) },
    'secret_key_base' => -> { SecureRandom.alphanumeric(64) },
    'admin_password' => -> { SecureRandom.alphanumeric(32) },
    'influx_password' => -> { SecureRandom.alphanumeric(32) },
    'influx_org' => -> { 'solectrus' },
    'influx_bucket' => -> { 'solectrus' },
    'influx_token' => -> { SecureRandom.hex(32) },
    'helios_secret_key_base' => -> { SecureRandom.hex(64) },
  }.freeze

  MANAGED_SERVICES = %i[postgresql redis influxdb dashboard watchtower helios].freeze

  def initialize(configuration)
    @configuration = configuration
  end

  def compose
    @compose ||= Compose.load
  end

  def env
    @env ||= Env.load
  end

  def write!
    create_data_directories!
    write_compose!
    write_env!
  end

  def compose_content
    build_compose
    compose.to_yaml
  end

  def env_content
    ensure_secrets!
    EnvContent.new(
      system_chapter,
      host_stack_path: Rails.configuration.helios_host_stack_path,
    ).to_s
  end

  private

  def stack_path
    Rails.configuration.helios_stack_path
  end

  def system_chapter
    @system_chapter ||= @configuration.chapter('system')
  end

  def service_configs
    @service_configs ||= ComposeContent.new(system_chapter)
  end

  def create_data_directories!
    DATA_DIRECTORIES.each do |dir|
      path = File.join(stack_path, dir)
      FileUtils.mkdir_p(path) unless File.directory?(path)
    end
  end

  def write_compose!
    backup_if_not_generated!(compose.path)
    ::File.write(compose.path, compose_content)
  end

  def build_compose
    compose.header_comment = compose_header_comment
    compose.name = 'solectrus'

    MANAGED_SERVICES.each do |name|
      compose.add_service(name, service_configs.public_send(name))
    end
  end

  def compose_header_comment
    sep = "# #{'=' * 60}"
    [
      sep,
      '# Generated by Helios — DO NOT EDIT MANUALLY!',
      '#',
      '# This file defines your SOLECTRUS Docker stack.',
      '# It is regenerated whenever you apply changes in Helios.',
      '# Use the Helios web interface to modify your configuration.',
      sep,
    ].join("\n")
  end

  def write_env!
    backup_if_not_generated!(Env.path)
    ::File.write(Env.path, env_content)
  end

  def backup_if_not_generated!(path)
    return unless ::File.exist?(path)
    return if ::File.read(path).include?(HELIOS_MARKER)

    ::FileUtils.cp(path, "#{path}.bak")
  end

  def ensure_secrets!
    missing = SECRET_DEFAULTS.reject { |key, _| system_chapter.key?(key) }
    updates = missing.transform_values(&:call)

    return if updates.empty?

    @configuration.update_chapter('system', system_chapter.merge(updates))
    @system_chapter = nil # Reset memoization so write_env! reads the updated chapter
  end
end
