class StackBuilder
  DATA_DIRECTORIES = %w[postgresql redis influxdb].freeze

  HELIOS_MARKER = 'Generated by Helios'.freeze

  SECRET_DEFAULTS = {
    'postgres_password' => -> { SecureRandom.alphanumeric(32) },
    'secret_key_base' => -> { SecureRandom.alphanumeric(64) },
    'admin_password' => -> { SecureRandom.alphanumeric(32) },
    'influx_password' => -> { SecureRandom.alphanumeric(32) },
    'influx_org' => -> { 'solectrus' },
    'influx_bucket' => -> { 'solectrus' },
    'influx_token' => -> { SecureRandom.hex(32) },
  }.freeze

  def initialize(configuration)
    @configuration = configuration
  end

  def compose
    @compose ||= Compose.load
  end

  def env
    @env ||= Env.load
  end

  def write!
    create_data_directories!
    write_compose!
    write_env!
  end

  private

  def stack_path
    Rails.configuration.helios_stack_path
  end

  def system_chapter
    @system_chapter ||= @configuration.chapter('system')
  end

  def unmanaged
    @unmanaged ||= @configuration.unmanaged
  end

  def create_data_directories!
    DATA_DIRECTORIES.each do |dir|
      path = File.join(stack_path, dir)
      FileUtils.mkdir_p(path) unless File.directory?(path)
    end
  end

  # Compose writing logic

  def write_compose!
    compose.header_comment = compose_header_comment
    compose.name = 'solectrus'

    add_postgresql_service
    add_redis_service
    add_influxdb_service
    add_dashboard_service
    add_unmanaged_services

    backup_if_unmanaged!(compose.path)
    compose.save
  end

  def compose_header_comment
    sep = "# #{'=' * 60}"
    [
      sep,
      '# Generated by Helios — DO NOT EDIT MANUALLY!',
      '#',
      '# This file defines your SOLECTRUS Docker stack.',
      '# It is regenerated whenever you apply changes in Helios.',
      '# Use the Helios web interface to modify your configuration.',
      sep,
    ].join("\n")
  end

  def add_postgresql_service
    compose.add_service('postgresql', postgresql_config)
  end

  def add_redis_service
    compose.add_service('redis', redis_config)
  end

  def add_influxdb_service
    compose.add_service('influxdb', influxdb_config)
  end

  def add_dashboard_service
    compose.add_service('dashboard', dashboard_config)
  end

  def add_unmanaged_services
    unmanaged['services']&.each do |name, config|
      compose.add_service(name, config)
    end
  end

  def postgresql_config
    {
      image: system_chapter['postgresql_image'] || 'postgres:18-alpine',
      environment: {
        'POSTGRES_PASSWORD' => '${POSTGRES_PASSWORD}',
        'POSTGRES_DB' => 'solectrus',
      },
      volumes: ['./postgresql:/var/lib/postgresql'],
      restart: 'unless-stopped',
      healthcheck: healthcheck_config('CMD-SHELL', 'pg_isready -U postgres'),
    }
  end

  def redis_config
    {
      image: system_chapter['redis_image'] || 'redis:8-alpine',
      volumes: ['./redis:/data'],
      restart: 'unless-stopped',
      healthcheck: healthcheck_config('CMD', 'redis-cli', 'ping'),
    }
  end

  def influxdb_config
    {
      image: system_chapter['influxdb_image'] || 'influxdb:2-alpine',
      ports: ['8086:8086'],
      environment: influxdb_environment,
      volumes: ['./influxdb:/var/lib/influxdb2'],
      restart: 'unless-stopped',
      healthcheck: healthcheck_config('CMD', 'influx', 'ping'),
    }
  end

  def influxdb_environment
    {
      'DOCKER_INFLUXDB_INIT_MODE' => 'setup',
      'DOCKER_INFLUXDB_INIT_USERNAME' => 'admin',
      'DOCKER_INFLUXDB_INIT_PASSWORD' => '${INFLUX_PASSWORD}',
      'DOCKER_INFLUXDB_INIT_ORG' => '${INFLUX_ORG}',
      'DOCKER_INFLUXDB_INIT_BUCKET' => '${INFLUX_BUCKET}',
      'DOCKER_INFLUXDB_INIT_ADMIN_TOKEN' => '${INFLUX_TOKEN}',
    }
  end

  def dashboard_config
    {
      image: system_chapter['dashboard_image'] || 'ghcr.io/solectrus/solectrus:latest',
      ports: ['3000:3000'],
      environment: dashboard_environment,
      depends_on: healthy_depends_on(%i[postgresql redis influxdb]),
      restart: 'unless-stopped',
      healthcheck: {
        test: ['CMD-SHELL', 'nc -z 127.0.0.1 3000 || exit 1'],
        interval: '10s',
        timeout: '5s',
        retries: 3,
      },
    }
  end

  def dashboard_environment
    common_environment
      .merge(influx_client_environment)
      .merge(database_environment)
      .merge(
        'DB_DATABASE' => 'solectrus',
        'SECRET_KEY_BASE' => '${SECRET_KEY_BASE}',
        'ADMIN_PASSWORD' => '${ADMIN_PASSWORD}',
      )
  end

  def common_environment
    {
      'TZ' => '${TZ}',
      'INSTALLATION_DATE' => '${INSTALLATION_DATE}',
      'REDIS_URL' => 'redis://redis:6379',
    }
  end

  def influx_client_environment
    {
      'INFLUX_HOST' => 'influxdb',
      'INFLUX_TOKEN' => '${INFLUX_TOKEN}',
      'INFLUX_ORG' => '${INFLUX_ORG}',
      'INFLUX_BUCKET' => '${INFLUX_BUCKET}',
    }
  end

  def database_environment
    {
      'DB_HOST' => 'postgresql',
      'DB_USER' => 'postgres',
      'DB_PASSWORD' => '${POSTGRES_PASSWORD}',
    }
  end

  def healthcheck_config(*test_cmd)
    { test: test_cmd, interval: '10s', timeout: '5s', retries: 5 }
  end

  def healthy_depends_on(services)
    services.index_with { { condition: 'service_healthy' } }
  end

  # Env writing logic

  def write_env!
    ensure_secrets!
    backup_if_unmanaged!(Env.path)
    ::File.write(Env.path, EnvContent.new(system_chapter, unmanaged).to_s)
  end

  # Backs up a file to <path>.bak if it exists but was not generated by Helios.
  # This protects manually maintained files when Helios takes over management.
  def backup_if_unmanaged!(path)
    return unless ::File.exist?(path)
    return if ::File.read(path).include?(HELIOS_MARKER)

    ::FileUtils.cp(path, "#{path}.bak")
  end

  # Generates any missing secrets/defaults and persists them to the system chapter in SQLite.
  # Secrets are never overwritten once set, ensuring stability across regenerations.
  def ensure_secrets!
    missing = SECRET_DEFAULTS.reject { |key, _| system_chapter.key?(key) }
    updates = missing.transform_values(&:call)

    return if updates.empty?

    @configuration.update_chapter('system', system_chapter.merge(updates))
    @system_chapter = nil # Reset memoization so write_env! reads the updated chapter
  end
end
