services:
  dashboard:
    image: ghcr.io/solectrus/solectrus:latest
    depends_on:
      postgresql:
        condition: service_healthy
      influxdb:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - 3000:3000
    environment:
      - TZ
      - APP_HOST
      - FORCE_SSL
      - SECRET_KEY_BASE
      - WEB_CONCURRENCY
      - INSTALLATION_DATE
      - ADMIN_PASSWORD
      - FRAME_ANCESTORS
      - UI_THEME
      - CO2_EMISSION_FACTOR
      - DB_HOST=postgresql
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_USER=postgres
      - REDIS_URL
      - INFLUX_HOST
      - INFLUX_TOKEN=${INFLUX_TOKEN_READ}
      - INFLUX_ORG
      - INFLUX_BUCKET
      - INFLUX_POLL_INTERVAL
      - INFLUX_SENSOR_INVERTER_POWER=
      - INFLUX_SENSOR_INVERTER_POWER_1=SENEC:mpp1_power
      - INFLUX_SENSOR_INVERTER_POWER_2=SENEC:mpp2_power
      - INFLUX_SENSOR_INVERTER_POWER_3=FRONIUS_inverter_1:power
      - INFLUX_SENSOR_INVERTER_POWER_4=FRONIUS_inverter_2:power
      - INFLUX_SENSOR_INVERTER_POWER_5=
      - INFLUX_SENSOR_GRID_IMPORT_POWER=SENEC:grid_power_plus
      - INFLUX_SENSOR_GRID_EXPORT_POWER=SENEC:grid_power_minus
      - INFLUX_SENSOR_GRID_EXPORT_LIMIT=SENEC_grid:export_limit
      - INFLUX_SENSOR_CASE_TEMP=SENEC:case_temp
      - INFLUX_SENSOR_SYSTEM_STATUS=SENEC:current_state
      - INFLUX_SENSOR_SYSTEM_STATUS_OK=SENEC:current_state_ok
      - INFLUX_SENSOR_BATTERY_SOC=SENEC:bat_fuel_charge     
      - INFLUX_SENSOR_BATTERY_CHARGING_POWER=SENEC:bat_power_plus
      - INFLUX_SENSOR_BATTERY_DISCHARGING_POWER=SENEC:bat_power_minus
      - INFLUX_SENSOR_HOUSE_POWER=HOUSE_POWER_CALCULATED:power
      - INFLUX_SENSOR_HEATPUMP_POWER=HEATPUMP_POWER_CALCULATED:power
      - INFLUX_SENSOR_HEATPUMP_HEATING_POWER=
      - INFLUX_SENSOR_HEATPUMP_TANK_TEMP=
      - INFLUX_SENSOR_HEATPUMP_TANK_TEMP_SETPOINT=
      - INFLUX_SENSOR_HEATPUMP_HEATPUMP_STATUS=
      - INFLUX_SENSOR_OUTDOOR_TEMP=
      - INFLUX_SENSOR_CUSTOM_POWER_01=MAIN_APARTMENT_POWER_CALCULATED:power
      - INFLUX_SENSOR_CUSTOM_POWER_02=GRANNY_FLAT_POWER_CALCULATED:power
      - INFLUX_SENSOR_CUSTOM_POWER_03=
      - INFLUX_SENSOR_CUSTOM_POWER_04=
      - INFLUX_SENSOR_CUSTOM_POWER_05=
      - INFLUX_SENSOR_CUSTOM_POWER_06=
      - INFLUX_SENSOR_CUSTOM_POWER_07=
      - INFLUX_SENSOR_CUSTOM_POWER_08=
      - INFLUX_SENSOR_CUSTOM_POWER_09=
      - INFLUX_SENSOR_CUSTOM_POWER_10=
      - INFLUX_SENSOR_CUSTOM_POWER_11=
      - INFLUX_SENSOR_CUSTOM_POWER_12=
      - INFLUX_SENSOR_CUSTOM_POWER_13=
      - INFLUX_SENSOR_CUSTOM_POWER_14=
      - INFLUX_SENSOR_CUSTOM_POWER_15=
      - INFLUX_SENSOR_CUSTOM_POWER_16=
      - INFLUX_SENSOR_CUSTOM_POWER_17=
      - INFLUX_SENSOR_CUSTOM_POWER_18=
      - INFLUX_SENSOR_CUSTOM_POWER_19=
      - INFLUX_SENSOR_CUSTOM_POWER_20=
      - INFLUX_SENSOR_WALLBOX_POWER=SENEC:wallbox_charge_power
      - INFLUX_SENSOR_WALLBOX_CAR_CONNECTED=
      - INFLUX_SENSOR_CAR_BATTERY_SOC=
      - INFLUX_EXCLUDE_FROM_HOUSE_POWER=
      - INFLUX_SENSOR_INVERTER_POWER_FORECAST=
    healthcheck:
      test:
        - CMD-SHELL
        - nc -z 127.0.0.1 3000 || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
    labels:
      - com.centurylinklabs.watchtower.scope=solectrus
  mqtt-collector:
    image: ghcr.io/solectrus/mqtt-collector:latest
    environment:
      - TZ
      - INFLUX_SCHEMA
      - INFLUX_HOST=influxdb
      - INFLUX_TOKEN=IIIII
      - INFLUX_ORG=DDDDD
      - INFLUX_BUCKET=DDDDD
      - INFLUX_PORT
      - MQTT_HOST=192.168.1.39
      - MQTT_PORT=1883
      - MQTT_SSL=false
      - MQTT_USERNAME=IIIII
      - MQTT_PASSWORD=IIIII
    logging:
      options:
        max-size: 10m
        max-file: '3'
    restart: unless-stopped
    depends_on:
      influxdb:
        condition: service_healthy
    links:
      - influxdb
    labels:
      - com.centurylinklabs.watchtower.scope=solectrus
  influxdb:
    image: influxdb:2-alpine
    volumes:
      - ${INFLUX_VOLUME_PATH}:/var/lib/influxdb2
    environment:
      - TZ
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUX_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUX_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUX_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUX_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUX_ADMIN_TOKEN}
    command: influxd run --bolt-path /var/lib/influxdb2/influxd.bolt --engine-path /var/lib/influxdb2/engine --store disk
    restart: unless-stopped
    healthcheck:
      test:
        - CMD
        - influx
        - ping
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
    ports:
      - 8086:8086
    labels:
      - com.centurylinklabs.watchtower.scope=solectrus
  postgresql:
    image: postgres:18-alpine
    environment:
      - TZ
      - POSTGRES_PASSWORD
    volumes:
      - ${DB_VOLUME_PATH}:/var/lib/postgresql
    restart: unless-stopped
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U postgres
      interval: 10s
      timeout: 20s
      retries: 5
      start_period: 60s
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
    labels:
      - com.centurylinklabs.watchtower.scope=solectrus
  redis:
    image: redis:8-alpine
    environment:
      - TZ
    volumes:
      - ${REDIS_VOLUME_PATH}:/data
    restart: unless-stopped
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      interval: 10s
      timeout: 20s
      retries: 5
      start_period: 60s
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
    labels:
      - com.centurylinklabs.watchtower.scope=solectrus
  forecast-collector:
    image: ghcr.io/solectrus/forecast-collector:latest
    environment:
      - TZ
      - FORECAST_PROVIDER
      - FORECAST_LATITUDE
      - FORECAST_LONGITUDE
      - FORECAST_DECLINATION
      - FORECAST_AZIMUTH
      - FORECAST_KWP
      - FORECAST_CONFIGURATIONS
      - FORECAST_0_DECLINATION
      - FORECAST_0_AZIMUTH
      - FORECAST_0_KWP
      - FORECAST_1_DECLINATION
      - FORECAST_1_AZIMUTH
      - FORECAST_1_KWP
      - FORECAST_2_DECLINATION
      - FORECAST_2_AZIMUTH
      - FORECAST_2_KWP
      - FORECAST_3_DECLINATION
      - FORECAST_3_AZIMUTH
      - FORECAST_3_KWP
      - FORECAST_INTERVAL
      - FORECAST_SOLAR_APIKEY
      - FORECAST_DAMPING_MORNING
      - FORECAST_DAMPING_EVENING
      - FORECAST_HORIZON
      - FORECAST_INVERTER
      - SOLCAST_APIKEY
      - SOLCAST_SITE
      - SOLCAST_0_SITE
      - SOLCAST_1_SITE
      - INFLUX_HOST
      - INFLUX_PORT
      - INFLUX_SCHEMA
      - INFLUX_TOKEN=${INFLUX_TOKEN_WRITE}
      - INFLUX_ORG
      - INFLUX_BUCKET
      - INFLUX_MEASUREMENT=${INFLUX_MEASUREMENT_FORECAST}
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
    depends_on:
      influxdb:
        condition: service_healthy
    labels:
      - com.centurylinklabs.watchtower.scope=solectrus
  power-splitter:
    image: ghcr.io/solectrus/power-splitter:latest
    environment:
      - TZ
      - INSTALLATION_DATE
      - INFLUX_HOST
      - INFLUX_SCHEMA
      - INFLUX_PORT
      - INFLUX_TOKEN=${INFLUX_ADMIN_TOKEN}
      - INFLUX_ORG
      - INFLUX_BUCKET
      - INFLUX_SENSOR_HOUSE_POWER=HOUSE_POWER_CALCULATED:power
      - INFLUX_SENSOR_GRID_IMPORT_POWER=SENEC:grid_power_plus
      - INFLUX_SENSOR_WALLBOX_POWER
      - INFLUX_SENSOR_BATTERY_CHARGING_POWER=SENEC:bat_power_plus
      - INFLUX_SENSOR_HEATPUMP_POWER=HEATPUMP_POWER_CALCULATED:power
      - INFLUX_SENSOR_HEATPUMP_HEATING_POWER
      - INFLUX_SENSOR_CUSTOM_POWER_01=MAIN_APARTMENT_POWER_CALCULATED:power
      - INFLUX_SENSOR_CUSTOM_POWER_02=GRANNY_FLAT_POWER_CALCULATED:power
      - INFLUX_SENSOR_CUSTOM_POWER_03
      - INFLUX_SENSOR_CUSTOM_POWER_04
      - INFLUX_SENSOR_CUSTOM_POWER_05
      - INFLUX_SENSOR_CUSTOM_POWER_06
      - INFLUX_SENSOR_CUSTOM_POWER_07
      - INFLUX_SENSOR_CUSTOM_POWER_08
      - INFLUX_SENSOR_CUSTOM_POWER_09
      - INFLUX_SENSOR_CUSTOM_POWER_10
      - INFLUX_SENSOR_CUSTOM_POWER_11
      - INFLUX_SENSOR_CUSTOM_POWER_12
      - INFLUX_SENSOR_CUSTOM_POWER_13
      - INFLUX_SENSOR_CUSTOM_POWER_14
      - INFLUX_SENSOR_CUSTOM_POWER_15
      - INFLUX_SENSOR_CUSTOM_POWER_16
      - INFLUX_SENSOR_CUSTOM_POWER_17
      - INFLUX_SENSOR_CUSTOM_POWER_18
      - INFLUX_SENSOR_CUSTOM_POWER_19
      - INFLUX_SENSOR_CUSTOM_POWER_20
      - INFLUX_EXCLUDE_FROM_HOUSE_POWER
      - REDIS_URL
      - DB_HOST=postgresql
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_USER=postgres
      - POWER_SPLITTER_INTERVAL
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
    restart: unless-stopped
    depends_on:
      influxdb:
        condition: service_healthy
    labels:
      - com.centurylinklabs.watchtower.scope=solectrus
  watchtower:
    image: nickfedor/watchtower
    environment:
      - TZ
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --scope solectrus --cleanup
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
    labels:
      - com.centurylinklabs.watchtower.scope=solectrus
  senec-collector:
    image: ghcr.io/solectrus/senec-collector:latest
    environment:
      - TZ
      - SENEC_ADAPTER
      - SENEC_HOST=192.168.1.33
      - SENEC_SCHEMA
      - SENEC_INTERVAL
      - SENEC_LANGUAGE
      - SENEC_USERNAME
      - SENEC_PASSWORD
      - SENEC_TOTP_URI
      - INFLUX_HOST=influxdb
      - INFLUX_SCHEMA
      - INFLUX_PORT
      - INFLUX_TOKEN=${INFLUX_TOKEN_WRITE}
      - INFLUX_ORG=DDDDD
      - INFLUX_BUCKET=DDDDD
      - INFLUX_MEASUREMENT=${INFLUX_MEASUREMENT_SENEC}
    logging:
      driver: 'json-file'
      options:
        max-size: 10m
        max-file: '3'
    restart: unless-stopped
    depends_on:
      influxdb:
        condition: service_healthy
    links:
      - influxdb
    labels:
      - com.centurylinklabs.watchtower.scope=solectrus
