formatter:
  enabled: true
  indentWidth: 2
  maxLineLength: 120

  exclude:
    - 'public/**'
    - node_modules/**

  rewriter:
    # Pre-format rewriters (run before formatting)
    pre:
      - tailwind-class-sorter

    # Post-format rewriters (run after formatting)
    post: []
