load helpers

setup() {
  in_tmpdir
  helios_url() { printf 'http://192.0.2.7:3999'; }
}

@test "print_running_banner names a password generated by this run" {
  run print_running_banner 'freshly-generated'
  [ "$status" -eq 0 ]
  [[ "$output" == *"Initial admin password:  freshly-generated"* ]]
}

# The adoption path generates nothing: the stack keeps the password it already
# has. The banner says where that password lives, so the login needs no search.
@test "print_running_banner points at the .env when it generates no password" {
  run print_running_banner ''
  [ "$status" -eq 0 ]
  [[ "$output" == *"share the same admin password"* ]]
  [[ "$output" == *"ADMIN_PASSWORD"* ]]
}

# An existing secret must not reach the scrollback of what may be a remote
# session, so the .env is named but never read.
@test "print_running_banner never prints the password of an adopted stack" {
  printf 'SECRET_KEY_BASE=x\nADMIN_PASSWORD=from-the-env\n' >"$ENV_FILE"

  run print_running_banner ''
  [ "$status" -eq 0 ]
  [[ "$output" != *"from-the-env"* ]]
}

@test "print_running_banner names the URL in either case" {
  run print_running_banner ''
  [[ "$output" == *"http://192.0.2.7:3999"* ]]

  run print_running_banner 'freshly-generated'
  [[ "$output" == *"http://192.0.2.7:3999"* ]]
}
