RSpec.describe Export::Builder do
  before { with_config_yaml }

  let(:tmp_dir) { Rails.configuration.data_path }
  let(:compose_path) { File.join(tmp_dir, 'compose.yaml') }
  let(:env_path) { File.join(tmp_dir, '.env') }

  let(:configuration) do
    config = Configuration.current
    config.update('system', { 'installation_date' => '2024-01-15', 'timezone' => 'Europe/Berlin' })
    config
  end

  describe '#write!' do
    before { described_class.new(configuration).write! }

    it_behaves_like 'valid Docker Compose configuration'

    it 'creates compose.yaml and .env files' do
      expect(File.exist?(compose_path)).to be true
      expect(File.exist?(env_path)).to be true
    end

    it 'creates data directories' do
      expect(Dir.exist?(File.join(tmp_dir, 'postgresql'))).to be true
      expect(Dir.exist?(File.join(tmp_dir, 'redis'))).to be true
      expect(Dir.exist?(File.join(tmp_dir, 'influxdb'))).to be true
    end
  end

  describe 'compose file generation' do
    before { described_class.new(configuration).write! }

    it 'sets project name to solectrus' do
      compose = Compose.load
      expect(compose.name).to eq('solectrus')
    end

    it 'includes all required MVP services' do
      compose = Compose.load
      expect(compose.services.names).to contain_exactly(
        'postgresql',
        'redis',
        'influxdb',
        'dashboard',
        'watchtower',
        'helios',
      )
    end

    it 'configures postgresql with healthcheck' do
      compose = Compose.load
      postgresql = compose.services.find('postgresql')

      expect(postgresql.image).to eq('postgres:18-alpine')
      expect(postgresql.healthcheck).to include('test', 'interval')
    end

    it 'configures dashboard with depends_on' do
      compose = Compose.load
      dashboard = compose.services.find('dashboard')

      expect(dashboard.depends_on.keys).to include(
        'postgresql',
        'redis',
        'influxdb',
      )
    end

    it 'includes a generated-by header comment' do
      content = File.read(compose_path)
      expect(content).to include('Generated by Helios')
      expect(content).to include('DO NOT EDIT MANUALLY')
    end
  end

  describe 'env file generation' do
    before { described_class.new(configuration).write! }

    it 'sets user configuration' do
      env = Env.load
      expect(env['INSTALLATION_DATE']).to eq('2024-01-15')
      expect(env['TZ']).to eq('Europe/Berlin')
    end

    it 'generates secrets' do
      env = Env.load
      expect(env['POSTGRES_PASSWORD']).to be_present
      expect(env['INFLUX_PASSWORD']).to be_present
      expect(env['INFLUX_TOKEN']).to be_present
      expect(env['SECRET_KEY_BASE']).to be_present
      expect(env['ADMIN_PASSWORD']).to be_present
    end

    it 'generates secrets with correct lengths' do
      env = Env.load
      expect(env['POSTGRES_PASSWORD'].length).to eq(32)
      expect(env['SECRET_KEY_BASE'].length).to eq(128)
      expect(env['INFLUX_TOKEN'].length).to eq(64)
      expect(env['ADMIN_PASSWORD'].length).to eq(32)
    end

    it 'sets InfluxDB configuration' do
      env = Env.load
      expect(env['INFLUX_ORG']).to eq('solectrus')
      expect(env['INFLUX_BUCKET']).to eq('solectrus')
    end

    it 'includes a generated-by header comment' do
      content = File.read(env_path)
      expect(content).to include('Generated by Helios')
      expect(content).to include('DO NOT EDIT MANUALLY')
    end

    it 'includes inline comments for each variable' do
      content = File.read(env_path)
      expect(content).to include('# Timezone for all services')
      expect(content).to include('# Admin password')
      expect(content).to include('# Database password')
    end
  end

  describe 'overwrite behavior' do
    context 'when existing files were not generated by Helios' do
      before do
        File.write(compose_path, "name: solectrus\n")
        File.write(env_path, "TZ=Europe/Berlin\n")
        described_class.new(configuration).write!
      end

      it 'overwrites the files' do
        expect(File.read(compose_path)).to include('Generated by Helios')
        expect(File.read(env_path)).to include('Generated by Helios')
      end
    end

    context 'when no files exist yet' do
      before { described_class.new(configuration).write! }

      it 'does not create a backup for compose.yaml' do
        expect(File.exist?(File.join(tmp_dir, 'compose.yaml.bak'))).to be false
      end

      it 'does not create a backup for .env' do
        expect(File.exist?(File.join(tmp_dir, '.env.bak'))).to be false
      end
    end
  end

  describe 'with reverse_proxy configured' do
    before do
      configuration.update('reverse_proxy', {
                             'app_domain' => 'solar.example.com',
                           })
      described_class.new(configuration).write!
    end

    it_behaves_like 'valid Docker Compose configuration'

    it 'includes traefik service in compose.yaml' do
      compose = Compose.load
      expect(compose.services.names).to include('traefik')
    end

    it 'configures traefik with correct image' do
      compose = Compose.load
      traefik = compose.services.find('traefik')
      expect(traefik.image).to eq('traefik:v3')
    end

    it 'removes dashboard ports' do
      compose = Compose.load
      dashboard = compose.services.find('dashboard')
      expect(dashboard.ports).to be_blank
    end

    it 'adds traefik labels to dashboard' do
      compose = Compose.load
      dashboard = compose.services.find('dashboard')
      labels = dashboard.config['labels']
      expect(labels).to include('traefik.enable=true')
      expect(labels).to include(
        'traefik.http.routers.dashboard.rule=Host(`solar.example.com`)',
      )
    end

    it 'sets FORCE_SSL on dashboard' do
      compose = Compose.load
      dashboard = compose.services.find('dashboard')
      expect(dashboard.environment).to include('FORCE_SSL=true')
    end

    it 'includes APP_DOMAIN in .env' do
      env = Env.load
      expect(env['APP_DOMAIN']).to eq('solar.example.com')
    end

    it 'includes LETSENCRYPT_EMAIL in .env' do
      env = Env.load
      expect(env['LETSENCRYPT_EMAIL']).to eq('webmaster@solar.example.com')
    end

    it 'creates traefik data directory' do
      expect(Dir.exist?(File.join(tmp_dir, 'traefik'))).to be true
    end
  end

  describe 'without reverse_proxy configured' do
    before { described_class.new(configuration).write! }

    it 'does not include traefik service' do
      compose = Compose.load
      expect(compose.services.names).not_to include('traefik')
    end

    it 'includes dashboard ports' do
      compose = Compose.load
      dashboard = compose.services.find('dashboard')
      expect(dashboard.ports).to include('3000:3000')
    end

    it 'does not include APP_DOMAIN in .env' do
      content = File.read(env_path)
      expect(content).not_to include('APP_DOMAIN')
    end
  end

  describe 'with backup configured' do
    before do
      configuration.update('backup', {
                             'aws_access_key_id' => 'AKIAEXAMPLE',
                             'aws_secret_access_key' => 'secret123',
                             'aws_region' => 'eu-central-1',
                             'aws_bucket' => 'my-bucket',
                           })
      described_class.new(configuration).write!
    end

    it_behaves_like 'valid Docker Compose configuration'

    it 'includes postgresql-backup service' do
      compose = Compose.load
      expect(compose.services.names).to include('postgresql-backup')
    end

    it 'includes influxdb-backup service' do
      compose = Compose.load
      expect(compose.services.names).to include('influxdb-backup')
    end

    it 'uses unless-stopped restart policies for backup services' do
      compose = Compose.load

      expect(compose.services.find('postgresql-backup').restart).to eq('unless-stopped')
      expect(compose.services.find('influxdb-backup').restart).to eq('unless-stopped')
    end

    it 'configures influxdb-backup with required environment' do
      compose = Compose.load
      influxdb_backup = compose.services.find('influxdb-backup')

      expect(influxdb_backup.environment).to include(
        'INFLUXDB_HOST=influxdb',
        'INFLUXDB_ORG=${INFLUX_ORG}',
        'INFLUXDB_TOKEN=${INFLUX_TOKEN}',
        'S3_BUCKET=${AWS_BUCKET}',
        'S3_PREFIX=influxdb_backup',
        'CRON=0 0 * * 0',
      )
      expect(influxdb_backup.environment).not_to include('AWS_REGION')
      expect(influxdb_backup.environment).not_to include('AWS_BUCKET' => '${AWS_BUCKET}')
    end

    it 'includes AWS credentials in .env' do
      env = Env.load
      expect(env['AWS_ACCESS_KEY_ID']).to eq('AKIAEXAMPLE')
      expect(env['AWS_SECRET_ACCESS_KEY']).to eq('secret123')
      expect(env['AWS_REGION']).to eq('eu-central-1')
      expect(env['AWS_BUCKET']).to eq('my-bucket')
    end
  end

  describe 'without backup configured' do
    before { described_class.new(configuration).write! }

    it 'does not include backup services' do
      compose = Compose.load
      expect(compose.services.names).not_to include('postgresql-backup', 'influxdb-backup')
    end

    it 'does not include AWS credentials in .env' do
      content = File.read(env_path)
      expect(content).not_to include('AWS_ACCESS_KEY_ID')
    end
  end

  describe 'with SENEC local configured' do
    before do
      configuration.update('senec', {
                             'adapter' => 'local',
                             'host' => '192.168.1.100',
                             'schema' => 'https',
                             'language' => 'de',
                             'interval' => '5',
                           })
      configuration.update_sensor('inverter_power', { 'source' => 'senec' })
      described_class.new(Configuration.current).write!
    end

    it_behaves_like 'valid Docker Compose configuration'

    it 'includes senec-collector service' do
      compose = Compose.load
      expect(compose.services.names).to include('senec-collector')
    end

    it 'configures senec-collector with environment' do
      compose = Compose.load
      senec = compose.services.find('senec-collector')

      expect(senec.environment).to include('SENEC_ADAPTER', 'SENEC_HOST', 'SENEC_SCHEMA', 'SENEC_LANGUAGE')
    end

    it 'includes SENEC variables in .env' do
      env = Env.load
      expect(env['SENEC_ADAPTER']).to eq('local')
      expect(env['SENEC_HOST']).to eq('192.168.1.100')
    end

    it 'includes sensor mappings in .env' do
      content = File.read(env_path)
      expect(content).to include('INFLUX_SENSOR_INVERTER_POWER')
    end
  end

  describe 'with SENEC cloud configured' do
    before do
      configuration.update('senec', {
                             'adapter' => 'cloud',
                             'username' => 'user@example.com',
                             'password' => 'secret',
                             'totp_uri' => 'otpauth://totp/SENEC',
                             'system_id' => '12345',
                             'ignore' => 'wallbox',
                           })
      configuration.update_sensor('inverter_power', { 'source' => 'senec' })
      described_class.new(Configuration.current).write!
    end

    it_behaves_like 'valid Docker Compose configuration'

    it 'includes cloud credentials in .env' do
      env = Env.load
      expect(env['SENEC_ADAPTER']).to eq('cloud')
      expect(env['SENEC_USERNAME']).to eq('user@example.com')
      expect(env['SENEC_PASSWORD']).to eq('secret')
    end

    it 'includes optional cloud variables in .env' do
      env = Env.load
      expect(env['SENEC_TOTP_URI']).to eq('otpauth://totp/SENEC')
      expect(env['SENEC_SYSTEM_ID']).to eq('12345')
      expect(env['SENEC_IGNORE']).to eq('wallbox')
    end

    it 'includes cloud vars in senec-collector environment' do
      compose = Compose.load
      senec = compose.services.find('senec-collector')

      expect(senec.environment).to include('SENEC_USERNAME', 'SENEC_PASSWORD')
      expect(senec.environment).to include('SENEC_TOTP_URI', 'SENEC_SYSTEM_ID', 'SENEC_IGNORE')
    end
  end

  describe 'with forecast configured' do
    before do
      configuration.update('forecast', {
                             'forecast' => 'forecast.solar',
                             'forecast_latitude' => '51.3',
                             'forecast_longitude' => '9.5',
                             'forecast_declination1' => '30',
                             'forecast_azimuth1' => '180',
                             'forecast_kwp1' => '10',
                             'forecast_interval' => '900',
                             'forecast_solar_apikey' => 'abc123',
                           })
      configuration.update_sensor('inverter_power_forecast', { 'source' => 'forecast' })
      described_class.new(Configuration.current).write!
    end

    it_behaves_like 'valid Docker Compose configuration'

    it 'includes forecast-collector service' do
      compose = Compose.load
      expect(compose.services.names).to include('forecast-collector')
    end

    it 'includes forecast variables in .env' do
      env = Env.load
      expect(env['FORECAST_PROVIDER']).to eq('forecast.solar')
      expect(env['FORECAST_LATITUDE']).to eq('51.3')
      expect(env['FORECAST_DECLINATION']).to eq('30')
      expect(env['FORECAST_KWP']).to eq('10')
      expect(env['FORECAST_SOLAR_APIKEY']).to eq('abc123')
    end

    it 'configures forecast-collector with environment' do
      compose = Compose.load
      forecast = compose.services.find('forecast-collector')

      expect(forecast.environment).to include(
        'FORECAST_PROVIDER', 'FORECAST_LATITUDE', 'FORECAST_LONGITUDE',
        'FORECAST_DECLINATION', 'FORECAST_AZIMUTH', 'FORECAST_KWP'
      )
    end
  end

  describe 'with multi-roof forecast configured' do
    before do
      configuration.update('forecast', {
                             'forecast' => 'forecast.solar',
                             'forecast_latitude' => '51.3',
                             'forecast_longitude' => '9.5',
                             'forecast_roofs' => '2',
                             'forecast_declination1' => '30',
                             'forecast_azimuth1' => '180',
                             'forecast_kwp1' => '5',
                             'forecast_declination2' => '25',
                             'forecast_azimuth2' => '-90',
                             'forecast_kwp2' => '3',
                           })
      configuration.update_sensor('inverter_power_forecast', { 'source' => 'forecast' })
      described_class.new(Configuration.current).write!
    end

    it_behaves_like 'valid Docker Compose configuration'

    it 'includes multi-roof configuration in .env' do
      env = Env.load
      expect(env['FORECAST_CONFIGURATIONS']).to eq('2')
      expect(env['FORECAST_0_DECLINATION']).to eq('30')
      expect(env['FORECAST_1_DECLINATION']).to eq('25')
    end

    it 'includes FORECAST_CONFIGURATIONS in compose environment' do
      compose = Compose.load
      forecast = compose.services.find('forecast-collector')

      expect(forecast.environment).to include('FORECAST_CONFIGURATIONS')
    end
  end

  describe 'with solcast forecast configured' do
    before do
      configuration.update('forecast', {
                             'forecast' => 'solcast',
                             'forecast_latitude' => '51.3',
                             'forecast_longitude' => '9.5',
                             'forecast_declination1' => '30',
                             'forecast_azimuth1' => '180',
                             'forecast_kwp1' => '10',
                             'forecast_solcast_api_key' => 'solcast-key',
                             'forecast_solcast_id1' => 'site-123',
                           })
      configuration.update_sensor('inverter_power_forecast', { 'source' => 'forecast' })
      described_class.new(Configuration.current).write!
    end

    it_behaves_like 'valid Docker Compose configuration'

    it 'includes solcast variables in .env' do
      env = Env.load
      expect(env['SOLCAST_APIKEY']).to eq('solcast-key')
      expect(env['SOLCAST_SITE']).to eq('site-123')
    end
  end

  describe 'with pvnode forecast configured' do
    before do
      configuration.update('forecast', {
                             'forecast' => 'pvnode',
                             'forecast_latitude' => '51.3',
                             'forecast_longitude' => '9.5',
                             'forecast_declination1' => '30',
                             'forecast_azimuth1' => '180',
                             'forecast_kwp1' => '10',
                             'forecast_pvnode_apikey' => 'pvnode-key',
                             'forecast_pvnode_paid' => 'true',
                             'forecast_pvnode_extra_params' => 'extra=1',
                           })
      configuration.update_sensor('inverter_power_forecast', { 'source' => 'forecast' })
      described_class.new(Configuration.current).write!
    end

    it_behaves_like 'valid Docker Compose configuration'

    it 'includes pvnode variables in .env' do
      env = Env.load
      expect(env['PVNODE_APIKEY']).to eq('pvnode-key')
      expect(env['PVNODE_PAID']).to eq('true')
      expect(env['PVNODE_EXTRA_PARAMS']).to eq('extra=1')
    end

    it 'includes pvnode vars in compose environment' do
      compose = Compose.load
      forecast = compose.services.find('forecast-collector')

      expect(forecast.environment).to include('PVNODE_APIKEY', 'PVNODE_PAID', 'PVNODE_EXTRA_PARAMS')
    end
  end

  describe 'with forecast optional fields configured' do
    before do
      configuration.update('forecast', {
                             'forecast' => 'forecast.solar',
                             'forecast_latitude' => '51.3',
                             'forecast_longitude' => '9.5',
                             'forecast_declination1' => '30',
                             'forecast_azimuth1' => '180',
                             'forecast_kwp1' => '10',
                             'forecast_damping_morning' => '0.5',
                             'forecast_damping_evening' => '0.8',
                             'forecast_horizon' => '24',
                             'forecast_inverter' => '0.95',
                           })
      configuration.update_sensor('inverter_power_forecast', { 'source' => 'forecast' })
      described_class.new(Configuration.current).write!
    end

    it_behaves_like 'valid Docker Compose configuration'

    it 'includes optional forecast variables in .env' do
      env = Env.load
      expect(env['FORECAST_DAMPING_MORNING']).to eq('0.5')
      expect(env['FORECAST_DAMPING_EVENING']).to eq('0.8')
      expect(env['FORECAST_HORIZON']).to eq('24')
      expect(env['FORECAST_INVERTER']).to eq('0.95')
    end

    it 'includes optional vars in compose environment' do
      compose = Compose.load
      forecast = compose.services.find('forecast-collector')

      expect(forecast.environment).to include(
        'FORECAST_DAMPING_MORNING', 'FORECAST_DAMPING_EVENING',
        'FORECAST_HORIZON', 'FORECAST_INVERTER'
      )
    end
  end

  describe 'with shelly configured' do
    before do
      configuration.update('shelly', { 'interval' => '5' })
      configuration.update_sensor('heatpump_power', {
                                    'source' => 'shelly',
                                    'shelly_host' => 'shelly-hp.local',
                                    'measurement' => 'heatpump',
                                    'shelly_interval' => '5',
                                  })
      described_class.new(Configuration.current).write!
    end

    it_behaves_like 'valid Docker Compose configuration'

    it 'includes shelly-collector service' do
      compose = Compose.load
      expect(compose.services.names).to include('shelly-collector')
    end

    it 'configures shelly-collector with host environment' do
      compose = Compose.load
      shelly = compose.services.find('shelly-collector')

      expect(shelly.environment).to include('SHELLY_HOST', 'INFLUX_MEASUREMENT')
    end

    it 'includes shelly variables in .env' do
      env = Env.load
      expect(env['SHELLY_HOST']).to eq('shelly-hp.local')
      expect(env['INFLUX_MEASUREMENT']).to eq('heatpump')
    end
  end

  describe 'with MQTT configured' do
    before do
      configuration.update('mqtt', {
                             'mqtt_host' => '192.168.1.50',
                             'mqtt_port' => '1883',
                             'mqtt_username' => 'mqttuser',
                             'mqtt_password' => 'mqttpass',
                           })
      configuration.update_sensor('inverter_power', {
                                    'source' => 'mqtt',
                                    'mqtt_topic' => 'solar/inverter',
                                    'measurement' => 'PV',
                                    'field' => 'power',
                                    'mqtt_payload_type' => 'json',
                                    'mqtt_json_key' => 'value',
                                  })
      described_class.new(Configuration.current).write!
    end

    it_behaves_like 'valid Docker Compose configuration'

    it 'includes mqtt-collector service' do
      compose = Compose.load
      expect(compose.services.names).to include('mqtt-collector')
    end

    it 'includes MQTT variables in .env' do
      env = Env.load
      expect(env['MQTT_HOST']).to eq('192.168.1.50')
      expect(env['MQTT_PORT']).to eq('1883')
      expect(env['MQTT_USERNAME']).to eq('mqttuser')
    end

    it 'includes mapping variables in compose environment' do
      compose = Compose.load
      mqtt = compose.services.find('mqtt-collector')

      expect(mqtt.environment).to include(
        'MAPPING_0_TOPIC',
        'MAPPING_0_MEASUREMENT',
        'MAPPING_0_FIELD',
        'MAPPING_0_TYPE',
        'MAPPING_0_JSON_KEY',
      )
    end

    it 'includes mapping variables in .env' do
      env = Env.load
      expect(env['MAPPING_0_TOPIC']).to eq('solar/inverter')
      expect(env['MAPPING_0_MEASUREMENT']).to eq('PV')
      expect(env['MAPPING_0_FIELD']).to eq('power')
      expect(env['MAPPING_0_TYPE']).to eq('json')
      expect(env['MAPPING_0_JSON_KEY']).to eq('value')
    end
  end

  describe 'with power-splitter configured' do
    before do
      configuration.update_sensor('inverter_power_1', { 'source' => 'senec' })
      configuration.update_sensor('inverter_power_2', { 'source' => 'senec' })
      configuration.update('senec', { 'adapter' => 'local', 'host' => '192.168.1.100' })
      described_class.new(Configuration.current).write!
    end

    it_behaves_like 'valid Docker Compose configuration'

    it 'includes power-splitter service' do
      compose = Compose.load
      expect(compose.services.names).to include('power-splitter')
    end

    it 'configures power-splitter with sensor environment' do
      compose = Compose.load
      splitter = compose.services.find('power-splitter')

      expect(splitter.environment).to include('INFLUX_SENSOR_INVERTER_POWER_1')
      expect(splitter.environment).to include('INFLUX_SENSOR_INVERTER_POWER_2')
    end
  end

  describe 'secret persistence' do
    it 'persists generated secrets to config.yaml' do
      described_class.new(configuration).write!

      reloaded = Configuration.current
      expect(reloaded.system.admin_password).to be_present
      expect(reloaded.system.secret_key_base).to be_present
      expect(reloaded.postgresql.password).to be_present
      expect(reloaded.influxdb.password).to be_present
      expect(reloaded.influxdb.token).to be_present
    end

    it 'preserves secrets across multiple writes' do
      described_class.new(configuration).write!
      first_password = Configuration.current.postgresql.password

      # Reload configuration from disk for second write
      config2 = Configuration.current
      described_class.new(config2).write!
      second_password = Configuration.current.postgresql.password

      expect(second_password).to eq(first_password)
    end

    it 'uses existing secrets instead of generating new ones' do
      configuration.update(
        'postgresql',
        configuration.postgresql.merge('password' => 'my-existing-secret'),
      )

      described_class.new(Configuration.current).write!

      env = Env.load
      expect(env['POSTGRES_PASSWORD']).to eq('my-existing-secret')
    end
  end
end
