module Export
  class Builder
    # Sections whose defaults are only generated on demand. The lambda decides
    # whether defaults should be written for this section given the current
    # configuration. Sections not listed here are always populated with defaults.
    LOCAL_STACK_ONLY = ->(config) { !config.collectors_only? }
    OPTIONAL_SECTIONS = {
      'backup' => ->(config) { config.configured?('backup') },
      'ingest' => ->(config) { config.ingest_required? },
      'dashboard' => LOCAL_STACK_ONLY,
      'postgresql' => LOCAL_STACK_ONLY,
      'influxdb' => LOCAL_STACK_ONLY,
      'redis' => LOCAL_STACK_ONLY,
    }.freeze

    def initialize(configuration)
      @configuration = configuration
    end

    def write!
      ensure_defaults!
      create_data_directories!
      write_compose!
      write_env!
    end

    # Regenerate compose.yaml/.env only if config.yaml is newer than either of
    # them (or they're missing). Catches drift from direct edits to config.yaml
    # without paying the write cost on every render.
    def write_if_stale!
      write! if stale?
    end

    def stale?
      source_mtime = mtime(Configuration.path)
      return false unless source_mtime

      [::Compose.path, ::Env.path].any? do |target|
        target_mtime = mtime(target)
        target_mtime.nil? || source_mtime > target_mtime
      end
    end

    def compose_content
      compose_builder.to_yaml
    end

    def env_content
      Env.new(@configuration).to_s
    end

    def traefik_content
      TraefikConfig.new(@configuration).to_s
    end

    # Materialize auto-generated values (passwords, tokens, …) into config.yaml
    # so compose_content/env_content reflect what would actually be written.
    # Public so a file preview can resolve defaults without writing the
    # compose.yaml/.env files themselves to disk (see Services::FilesController).
    def ensure_defaults!
      missing = ConfigSchema.missing_auto_generated(@configuration)
      return if missing.empty?

      missing.each do |section, defaults|
        gate = OPTIONAL_SECTIONS[section]
        next if gate && !gate.call(@configuration)

        current = @configuration.send(section).to_h
        # Resolve sequentially so a lambda for one key can see earlier
        # resolutions in the same section (e.g. admin_password ← secret_key_base).
        updates = {}
        defaults.each do |key, default|
          updates[key] = ConfigSchema.resolve_default(default, current.merge(updates))
        end
        link_influxdb_tokens!(updates) if section == 'influxdb'
        @configuration.update(section, current.merge(updates))
      end
    end

    private

    def data_path
      Rails.configuration.data_path
    end

    def compose_builder
      @compose_builder ||= Compose.new(@configuration)
    end

    def create_data_directories!
      compose_builder.data_directories.each do |dir|
        FileUtils.mkdir_p(File.join(data_path, dir))
      end
    end

    def write_compose!
      atomic_write(::Compose.path, compose_content)
    end

    def write_env!
      atomic_write(::Env.path, env_content)
    end

    def atomic_write(path, content)
      tmp_path = "#{path}.tmp"
      ::File.write(tmp_path, content)
      ::File.rename(tmp_path, path)
    end

    def mtime(path)
      ::File.mtime(path)
    rescue Errno::ENOENT
      nil
    end

    # A HELIOS-generated stack runs on a single shared token, even though the
    # schema keeps four role fields. InfluxDB OSS 2.x only accepts a
    # caller-supplied token value at `/api/v2/setup` (the admin token, seeded
    # by the docker-entrypoint from DOCKER_INFLUXDB_INIT_ADMIN_TOKEN). Every
    # further authorization gets its value generated by the server and handed
    # back in the response — it cannot be dictated up front. Distinct
    # role tokens would therefore need a post-start provisioning step (boot
    # InfluxDB, POST /api/v2/authorizations, write the returned values back to
    # config.yaml, re-export .env, restart the dependent services), which we
    # deliberately don't do: all four tokens sit in the same .env on the same
    # host anyway, so the isolation gained does not pay for an extra
    # failure-prone bootstrap stage.
    #
    # So the fields exist for lossless import of *foreign* stacks that already
    # use privilege-separated authorizations (see ConfigSchema and
    # ConfigurationMigrations::SplitInfluxdbTokens). For anything HELIOS mints
    # itself the four .env entries must share one value, or collectors and
    # dashboard would authenticate against tokens InfluxDB never issued.
    def link_influxdb_tokens!(updates)
      tokens = updates.slice(*ConfigSchema::INFLUXDB_TOKEN_FIELDS)
      return if tokens.empty?

      shared = tokens.values.first
      ConfigSchema::INFLUXDB_TOKEN_FIELDS.each do |field|
        updates[field] = shared if updates.key?(field)
      end
    end
  end
end
