module Export
  class Compose
    WATCHTOWER_LABEL = 'com.centurylinklabs.watchtower.scope=solectrus'.freeze

    BASE_SERVICES = [
      Services::Dashboard,
      Services::Influxdb,
      Services::Postgresql,
      Services::Redis,
      Services::Watchtower,
      Services::Helios,
    ].freeze

    CONDITIONAL_SERVICES = [
      Services::Traefik,
      Services::PostgresqlBackup,
      Services::InfluxdbBackup,
      Services::SenecCollector,
      Services::ShellyCollector,
      Services::MqttCollector,
      Services::ForecastCollector,
      Services::PowerSplitter,
    ].freeze

    def initialize(configuration)
      @configuration = configuration
    end

    def to_yaml
      compose = ::Compose::File.new(::Compose.path)
      compose.header_comment = compose_header_comment
      compose.name = 'solectrus'

      add_class_based_services(compose)
      add_unmanaged_services(compose)

      compose.to_yaml
    end

    def data_directories
      active_service_classes.flat_map(&:data_directories).uniq
    end

    private

    attr_reader :configuration

    def add_class_based_services(compose)
      active_service_classes.each do |service_class|
        service_hash = service_class.new(configuration).to_h.reverse_merge(default_logging)
        service_hash[:labels] = Array(service_hash[:labels]) + [WATCHTOWER_LABEL]

        compose.add_service(
          service_class.service_name,
          service_hash,
          comment: service_class.comment,
        )
      end
    end

    def active_service_classes
      @active_service_classes ||= [
        *BASE_SERVICES,
        *CONDITIONAL_SERVICES.select { |service_class| service_class.enabled?(configuration) },
      ]
    end

    def add_unmanaged_services(compose)
      unmanaged = configuration.unmanaged
      return if unmanaged.services.blank?

      unmanaged.services.each do |name, config|
        next if config.blank?

        compose.add_service(name, config.to_h, comment: 'Unmanaged service (preserved from existing installation)')
      end
    end

    def default_logging
      { logging: { driver: 'json-file', options: { 'max-size' => '10m', 'max-file' => '3' } } }
    end

    def compose_header_comment
      sep = Env::SEPARATOR
      [
        sep,
        '# Generated by Helios — DO NOT EDIT MANUALLY!',
        '#',
        '# This file defines your SOLECTRUS Docker stack.',
        '# It is regenerated whenever you apply changes in Helios.',
        '# Use the Helios web interface to modify your configuration.',
        sep,
      ].join("\n")
    end
  end
end
