module Export
  class Env
    SEPARATOR = "# #{'=' * 60}".freeze

    WARNING_BANNER = [
      SEPARATOR,
      '# DO NOT EDIT THIS FILE.',
      '#',
      '# This file is generated by HELIOS. Any manual change WILL be',
      '# overwritten — silently, without backup — the next time HELIOS',
      '# applies a configuration. In the worst case your edit breaks',
      '# the stack and HELIOS can no longer recover it.',
      '#',
      '# Change every setting through the HELIOS web interface.',
      '#',
      '# Missing a setting? HELIOS is actively developed and can be',
      '# extended — suggest it at:',
      '# https://github.com/solectrus/helios/issues',
      '#',
      '# HELIOS fits the vast majority of setups. For a very',
      '# specialized configuration, managing compose.yaml + .env',
      '# by hand instead remains a valid alternative.',
      SEPARATOR,
    ].join("\n").freeze

    SECTIONS = [
      [General,      ->(_) { true }],
      [Security,     ->(_) { true }],
      [Dashboard,    ->(c) { !c.collectors_only? }],
      [Postgresql,   ->(c) { !c.collectors_only? }],
      [Influxdb,     ->(_) { true }],
      [Redis,        ->(c) { !c.collectors_only? }],
      [ReverseProxy, ->(c) { Services::Traefik.enabled?(c) }],
      [PowerSplitter, ->(c) { Services::PowerSplitter.enabled?(c) }],
      [Senec,        ->(c) { Services::SenecCollector.enabled?(c) }],
      [Forecast,     ->(c) { Services::ForecastCollector.enabled?(c) }],
      [Mqtt,         ->(c) { Services::MqttCollector.enabled?(c) }],
      [Shelly,       ->(c) { Services::ShellyCollector.enabled?(c) }],
      [Ingest,       ->(c) { c.ingest_required? }],
      [Watchtower,   ->(_) { true }],
      [Sensors,      ->(_) { true }],
      [Unmanaged,    ->(_) { true }],
    ].freeze

    def initialize(configuration)
      @configuration = configuration
    end

    def to_s
      env_file = ::Env::File.new(::Env.path)
      env_file.header_comment = header_comment
      build(env_file)
      env_file.to_s
    end

    private

    attr_reader :configuration

    def build(env)
      enabled_sections.each { |section_class| section_class.new(env, configuration).call }
    end

    def enabled_sections
      SECTIONS.filter_map { |klass, enabled| klass if enabled.call(configuration) }
    end

    def header_comment
      "#{WARNING_BANNER}\n" # Trailing newline → blank line before first section
    end
  end
end
