module Export
  class Env # rubocop:disable Metrics/ClassLength
    SEPARATOR = "# #{'=' * 60}".freeze

    MQTT_OPTIONAL_ENTRIES = {
      'mqtt_port' => ['MQTT_PORT', 'MQTT broker port'],
      'mqtt_ssl' => ['MQTT_SSL', 'Enable SSL for MQTT connection'],
      'mqtt_username' => ['MQTT_USERNAME', 'MQTT broker username'],
      'mqtt_password' => ['MQTT_PASSWORD', 'MQTT broker password'],
    }.freeze

    def initialize(configuration)
      @configuration = configuration
    end

    def to_s
      env_file = ::Env::File.new(::Env.path)
      env_file.header_comment = header_comment
      build(env_file)
      env_file.to_s
    end

    private

    attr_reader :configuration

    def build(env) # rubocop:disable Metrics/AbcSize
      general_section(env)
      security_section(env)
      dashboard_section(env)
      postgresql_section(env)
      influxdb_section(env)
      helios_section(env)
      reverse_proxy_section(env) if Services::Traefik.enabled?(configuration)
      backup_section(env) if Services::PostgresqlBackup.enabled?(configuration)
      senec_section(env) if configuration.senec_required?
      forecast_section(env) if Services::ForecastCollector.enabled?(configuration)
      mqtt_section(env) if configuration.mqtt_required?
      shelly_section(env) if configuration.shelly_required?
      power_splitter_section(env)
      sensor_section(env)
      unmanaged_section(env)
    end

    def header_comment
      [
        SEPARATOR,
        '# Generated by Helios — DO NOT EDIT MANUALLY!',
        '#',
        '# This file is regenerated from the Helios configuration (config.yaml).',
        '# Use the Helios web interface to modify your configuration.',
        SEPARATOR,
      ].join("\n")
    end

    def general_section(env)
      env.add_section('General settings')
      entry(env, 'TZ', configuration.system.timezone,
            'Timezone for all services (IANA format, e.g. Europe/Berlin)')
      entry(env, 'INSTALLATION_DATE', configuration.system.installation_date,
            'Date of first solar installation (YYYY-MM-DD) — used for statistics and charts')
    end

    def security_section(env)
      env.add_section('Security')
      entry(env, 'ADMIN_PASSWORD', configuration.system.admin_password,
            'Admin password — shared by Dashboard and Helios')
      entry(env, 'SECRET_KEY_BASE', configuration.system.secret_key_base,
            'Secret key for Rails sessions — shared by Dashboard and Helios')
    end

    def dashboard_section(env)
      sys = configuration.system
      env.add_section('Dashboard')
      entry(env, 'APP_HOST', sys.app_host.presence || 'localhost',
            'Hostname for the SOLECTRUS web interface')
      entry(env, 'WEB_CONCURRENCY', sys.web_concurrency.presence || '0',
            'Number of web server processes (0 = single process)')
      entry(env, 'INFLUX_POLL_INTERVAL', sys.influx_poll_interval.presence || '5',
            'InfluxDB polling interval in seconds')
      dashboard_optional_entries(env, sys)
    end

    def dashboard_optional_entries(env, sys)
      optional_entry(env, 'CO2_EMISSION_FACTOR', sys.co2_emission_factor, 'CO2 emission factor (g/kWh)')
      optional_entry(env, 'FRAME_ANCESTORS', sys.frame_ancestors, 'Allowed frame ancestors for embedding')
      optional_entry(env, 'UI_THEME', sys.ui_theme, 'UI theme (light or dark)')
      optional_entry(env, 'LOCKUP_CODEWORD', sys.lockup_codeword, 'Codeword for lockup page protection')
      optional_entry(env, 'TRUSTED_PROXY_RANGES', sys.trusted_proxy_ranges, 'Trusted proxy IP ranges')
      excluded = configuration.excluded_from_house_power.join(',').presence
      optional_entry(env, 'INFLUX_EXCLUDE_FROM_HOUSE_POWER', excluded,
                     'Sensors excluded from house power calculation')
    end

    def postgresql_section(env)
      env.add_section('PostgreSQL database')
      entry(env, 'POSTGRES_PASSWORD', configuration.postgresql.password,
            'Database password — auto-generated, do not change after first start')
      env.add_blank_line
    end

    def influxdb_section(env)
      env.add_section('InfluxDB time-series database')
      entry(env, 'INFLUX_PASSWORD', configuration.influxdb.password,
            'Admin password — auto-generated, do not change after first start')
      entry(env, 'INFLUX_ORG', configuration.influxdb.org, 'Organization name')
      entry(env, 'INFLUX_BUCKET', configuration.influxdb.bucket,
            'Bucket (database) name for time-series data')
      entry(env, 'INFLUX_TOKEN', configuration.influxdb.token,
            'API token with full access — auto-generated, do not change after first start')
    end

    def helios_section(env)
      env.add_section('Helios')
      entry(env, 'HELIOS_HOST_STACK_PATH', Rails.configuration.helios_host_stack_path,
            'Path on the Docker host where stack files are stored')
    end

    def reverse_proxy_section(env)
      env.add_section('Reverse Proxy (Traefik)')
      entry(env, 'APP_DOMAIN', configuration.reverse_proxy.app_domain,
            'Domain for HTTPS access via Traefik')
      entry(env, 'LETSENCRYPT_EMAIL', Services::Traefik.letsencrypt_email(configuration),
            "Email for Let's Encrypt certificate notifications")
    end

    def backup_section(env)
      env.add_section('S3 Backup')
      entry(env, 'AWS_ACCESS_KEY_ID', configuration.backup.aws_access_key_id,
            'AWS access key for S3 backup')
      entry(env, 'AWS_SECRET_ACCESS_KEY', configuration.backup.aws_secret_access_key,
            'AWS secret key — keep this confidential!')
      entry(env, 'AWS_REGION', configuration.backup.aws_region,
            'AWS region for S3 bucket')
      entry(env, 'AWS_BUCKET', configuration.backup.aws_bucket,
            'S3 bucket name for backups')
    end

    def senec_section(env)
      senec = configuration.senec
      return if senec.blank?

      env.add_section('SENEC collector')
      entry(env, 'SENEC_ADAPTER', senec.adapter || 'local', 'SENEC adapter type (local or cloud)')
      if senec.adapter == 'cloud'
        senec_cloud_entries(env, senec)
      else
        senec_local_entries(env, senec)
      end
      entry(env, 'SENEC_INTERVAL', senec.interval || '5', 'Polling interval in seconds')
      if senec.ignore.present?
        entry(env, 'SENEC_IGNORE', senec.ignore,
              'Comma-separated fields to exclude from InfluxDB')
      end
      entry(env, 'INFLUX_MEASUREMENT_SENEC', 'SENEC', 'InfluxDB measurement name for SENEC')
    end

    def senec_cloud_entries(env, senec)
      entry(env, 'SENEC_USERNAME', senec.username, 'SENEC cloud username')
      entry(env, 'SENEC_PASSWORD', senec.password, 'SENEC cloud password')
      entry(env, 'SENEC_TOTP_URI', senec.totp_uri, 'SENEC TOTP URI for MFA') if senec.totp_uri.present?
      entry(env, 'SENEC_SYSTEM_ID', senec.system_id, 'SENEC system ID') if senec.system_id.present?
    end

    def senec_local_entries(env, senec)
      entry(env, 'SENEC_HOST', senec.host, 'SENEC device IP or hostname')
      entry(env, 'SENEC_SCHEMA', senec.schema || 'https', 'Connection protocol')
      entry(env, 'SENEC_LANGUAGE', senec.language || 'de', 'Status text language')
    end

    def forecast_section(env)
      fcast = configuration.forecast
      return if fcast.forecast.blank?

      env.add_section('Forecast')
      forecast_base_entries(env, fcast)
      forecast_roof_entries(env, fcast)
      forecast_provider_entries(env, fcast)
      entry(env, 'INFLUX_MEASUREMENT_FORECAST', 'Forecast', 'InfluxDB measurement name for forecasts')
    end

    def forecast_base_entries(env, fcast)
      entry(env, 'FORECAST_PROVIDER', fcast.forecast, 'Forecast provider')
      entry(env, 'FORECAST_LATITUDE', fcast.forecast_latitude, 'Solar panel latitude')
      entry(env, 'FORECAST_LONGITUDE', fcast.forecast_longitude, 'Solar panel longitude')
      entry(env, 'FORECAST_INTERVAL', fcast.forecast_interval || '900', 'Forecast update interval in seconds')
      forecast_optional_entries(env, fcast)
    end

    def forecast_optional_entries(env, fcast)
      optional_entry(env, 'FORECAST_DAMPING_MORNING', fcast.forecast_damping_morning,
                     'Damping factor for morning hours')
      optional_entry(env, 'FORECAST_DAMPING_EVENING', fcast.forecast_damping_evening,
                     'Damping factor for evening hours')
      optional_entry(env, 'FORECAST_HORIZON', fcast.forecast_horizon, 'Forecast horizon in hours')
      optional_entry(env, 'FORECAST_INVERTER', fcast.forecast_inverter, 'Inverter efficiency factor')
    end

    def forecast_roof_entries(env, fcast)
      roofs = (fcast.forecast_roofs || 1).to_i
      if roofs > 1
        forecast_multi_roof_entries(env, fcast, roofs)
      else
        forecast_single_roof_entries(env, fcast)
      end
    end

    def forecast_single_roof_entries(env, fcast)
      entry(env, 'FORECAST_DECLINATION', fcast.forecast_declination1, 'Roof tilt angle')
      entry(env, 'FORECAST_AZIMUTH', fcast.forecast_azimuth1, 'Roof orientation')
      entry(env, 'FORECAST_KWP', fcast.forecast_kwp1, 'System capacity in kWp')
    end

    def forecast_multi_roof_entries(env, fcast, roofs)
      entry(env, 'FORECAST_CONFIGURATIONS', roofs.to_s, 'Number of roof surfaces')
      roofs.times do |i|
        entry(env, "FORECAST_#{i}_DECLINATION", fcast.send("forecast_declination#{i + 1}"),
              "Roof surface #{i + 1} tilt angle")
        entry(env, "FORECAST_#{i}_AZIMUTH", fcast.send("forecast_azimuth#{i + 1}"),
              "Roof surface #{i + 1} orientation")
        entry(env, "FORECAST_#{i}_KWP", fcast.send("forecast_kwp#{i + 1}"),
              "Roof surface #{i + 1} capacity in kWp")
      end
    end

    def forecast_provider_entries(env, fcast)
      case fcast.forecast
      when 'forecast.solar'
        if fcast.forecast_solar_apikey.present?
          entry(env, 'FORECAST_SOLAR_APIKEY', fcast.forecast_solar_apikey,
                'Forecast.Solar API key')
        end
      when 'solcast'
        solcast_entries(env, fcast)
      when 'pvnode'
        pvnode_entries(env, fcast)
      end
    end

    def solcast_entries(env, fcast)
      roofs = (fcast.forecast_roofs || 1).to_i
      entry(env, 'SOLCAST_APIKEY', fcast.forecast_solcast_api_key, 'Solcast API key')
      entry(env, 'SOLCAST_SITE', fcast.forecast_solcast_id1, 'Solcast site ID')
      return unless roofs > 1

      entry(env, 'SOLCAST_0_SITE', fcast.forecast_solcast_id1, 'Solcast site 1 ID')
      entry(env, 'SOLCAST_1_SITE', fcast.forecast_solcast_id2, 'Solcast site 2 ID')
    end

    def pvnode_entries(env, fcast)
      entry(env, 'PVNODE_APIKEY', fcast.forecast_pvnode_apikey, 'pvnode API key')
      if fcast.forecast_pvnode_paid.present?
        entry(env, 'PVNODE_PAID', fcast.forecast_pvnode_paid,
              'pvnode paid account')
      end
      return if fcast.forecast_pvnode_extra_params.blank?

      entry(env, 'PVNODE_EXTRA_PARAMS', fcast.forecast_pvnode_extra_params, 'Additional pvnode parameters')
    end

    def mqtt_section(env)
      mqtt = configuration.mqtt
      env.add_section('MQTT broker')
      entry(env, 'MQTT_HOST', mqtt.mqtt_host, 'MQTT broker hostname')
      MQTT_OPTIONAL_ENTRIES.each do |field, (key, comment)|
        value = mqtt.send(field)
        entry(env, key, value, comment) if value.present?
      end
      mqtt_mapping_entries(env)
    end

    def mqtt_mapping_entries(env)
      sensors = configuration.sensors_with_source('mqtt')
      return if sensors.blank?

      sensors.each_with_index do |(_, config), index|
        Services::MqttCollector::MAPPING_FIELDS.each do |config_key, env_suffix|
          value = config[config_key]
          next if value.blank?

          entry(env, "MAPPING_#{index}_#{env_suffix}", value,
                "MQTT mapping #{index}: #{env_suffix.downcase}")
        end
      end
    end

    def shelly_section(env)
      sensors = configuration.sensors_with_source('shelly')
      return if sensors.blank?

      shelly = configuration.shelly
      env.add_section('Shelly collector')
      if shelly&.connection != 'cloud'
        entry(env, 'SHELLY_HOST', shelly_csv(sensors) { |_, config| config['shelly_host'] },
              'Shelly device hostnames (comma-separated)')
      end
      entry(env, 'SHELLY_INTERVAL', shelly&.interval || '5',
            'Polling interval in seconds')
      entry(env, 'INFLUX_MEASUREMENT', shelly_csv(sensors) { |_, config| config['measurement'] },
            'InfluxDB measurement names (comma-separated)')
      shelly_optional_entries(env, sensors, shelly)
    end

    def shelly_optional_entries(env, sensors, shelly)
      shelly_per_sensor_optional_entries(env, sensors)
      shelly_global_optional_entries(env, shelly)
    end

    def shelly_per_sensor_optional_entries(env, sensors)
      %w[shelly_password shelly_device_id shelly_invert_power].each do |field|
        values = sensors.map { |_, config| config[field].presence || '' }
        next unless values.any?(&:present?)

        entry(env, field.upcase, values.join(','), "Shelly #{field.sub('shelly_', '')} (comma-separated)")
      end
    end

    def shelly_global_optional_entries(env, shelly)
      return unless shelly&.connection == 'cloud'

      entry(env, 'SHELLY_CLOUD_SERVER', shelly.cloud_server,
            'Shelly Cloud server URL')
      return if shelly.auth_key.blank?

      entry(env, 'SHELLY_AUTH_KEY', shelly.auth_key,
            'Shelly Cloud authentication key')
    end

    def shelly_csv(sensors, &)
      sensors.map(&).join(',')
    end

    def power_splitter_section(env)
      interval = configuration.system.power_splitter_interval
      return if interval.blank?

      env.add_section('Power Splitter')
      entry(env, 'POWER_SPLITTER_INTERVAL', interval, 'Power splitter calculation interval in seconds')
    end

    def sensor_section(env)
      mappings = configuration.effective_sensor_mappings
      return if mappings.blank?

      env.add_section('Sensor mappings')
      SensorRegistry::SENSORS.each_key do |sensor|
        value = mappings[sensor]
        next if value.blank?

        entry(env, "INFLUX_SENSOR_#{sensor.upcase}", value, "Sensor: #{sensor}")
      end
    end

    def unmanaged_section(env)
      unmanaged = configuration.unmanaged
      return if unmanaged.env_vars.blank?

      env.add_section('Unmanaged variables (preserved from existing installation)')
      unmanaged.env_vars.each do |key, value|
        env[key] = value
        env.add_blank_line
      end
    end

    def entry(env, key, value, comment)
      env.add_comment(comment)
      env[key] = value
      env.add_blank_line
    end

    def optional_entry(env, key, value, comment)
      entry(env, key, value, comment) if value.present?
    end
  end
end
