class StackBuilder
  class EnvContent
    SEPARATOR = "# #{'=' * 60}".freeze

    def initialize(configuration)
      @configuration = configuration
    end

    def to_s
      sections = [
        *file_header_lines,
        *general_section_lines,
        *security_section_lines,
        *postgresql_section_lines,
        *influxdb_section_lines,
        *helios_section_lines,
      ]
      sections.concat(reverse_proxy_section_lines) if Services::Traefik.enabled?(configuration)
      sections.concat(backup_section_lines) if Services::PostgresqlBackup.enabled?(configuration)
      sections.join("\n")
    end

    private

    attr_reader :configuration

    def system_data
      configuration.system
    end

    def postgresql_data
      configuration.postgresql
    end

    def influxdb_data
      configuration.influxdb
    end

    def reverse_proxy_data
      configuration.reverse_proxy
    end

    def backup_data
      configuration.backup
    end

    def host_stack_path
      Rails.configuration.helios_host_stack_path
    end

    def file_header_lines
      [
        SEPARATOR,
        '# Generated by Helios — DO NOT EDIT MANUALLY!',
        '#',
        '# This file is regenerated from the Helios configuration (config.yaml).',
        '# Use the Helios web interface to modify your configuration.',
        SEPARATOR,
        '',
      ]
    end

    def general_section_lines
      [
        '# --- General settings ---',
        *entry('TZ', system_data.timezone,
               'Timezone for all services (IANA format, e.g. Europe/Berlin)'),
        *entry('INSTALLATION_DATE', system_data.installation_date,
               'Date of first solar installation (YYYY-MM-DD) — used for statistics and charts'),
      ]
    end

    def security_section_lines
      [
        '# --- Security ---',
        *entry('ADMIN_PASSWORD', system_data.admin_password,
               'Admin password for the SOLECTRUS web interface'),
        *entry('SECRET_KEY_BASE', system_data.secret_key_base,
               'Secret key for Rails sessions — shared by Dashboard and Helios'),
      ]
    end

    def postgresql_section_lines
      [
        '# --- PostgreSQL database ---',
        *entry('POSTGRES_PASSWORD', postgresql_data.password,
               'Database password — auto-generated, do not change after first start'),
        '',
      ]
    end

    def influxdb_section_lines
      [
        '# --- InfluxDB time-series database ---',
        *entry('INFLUX_PASSWORD', influxdb_data.password,
               'Admin password — auto-generated, do not change after first start'),
        *entry('INFLUX_ORG', influxdb_data.org, 'Organization name'),
        *entry('INFLUX_BUCKET', influxdb_data.bucket,
               'Bucket (database) name for time-series data'),
        *entry('INFLUX_TOKEN', influxdb_data.token,
               'API token with full access — auto-generated, do not change after first start'),
      ]
    end

    def helios_section_lines
      [
        '# --- Helios ---',
        *entry('HELIOS_HOST_STACK_PATH', host_stack_path,
               'Path on the Docker host where stack files are stored'),
      ]
    end

    def reverse_proxy_section_lines
      [
        '# --- Reverse Proxy (Traefik) ---',
        *entry('APP_DOMAIN', reverse_proxy_data.app_domain,
               'Domain for HTTPS access via Traefik'),
        *entry('LETSENCRYPT_EMAIL', Services::Traefik.letsencrypt_email(configuration),
               "Email for Let's Encrypt certificate notifications"),
      ]
    end

    def backup_section_lines
      [
        '# --- S3 Backup ---',
        *entry('AWS_ACCESS_KEY_ID', backup_data.aws_access_key_id,
               'AWS access key for S3 backup'),
        *entry('AWS_SECRET_ACCESS_KEY', backup_data.aws_secret_access_key,
               'AWS secret key — keep this confidential!'),
        *entry('AWS_REGION', backup_data.aws_region,
               'AWS region for S3 bucket'),
        *entry('AWS_BUCKET', backup_data.aws_bucket,
               'S3 bucket name for backups'),
      ]
    end

    # Returns three lines: a comment, the key=value assignment, and a blank line.
    def entry(key, value, comment)
      ["# #{comment}", "#{key}=#{value}", '']
    end
  end
end
