class StackBuilder
  class EnvContent
    SEPARATOR = "# #{'=' * 60}".freeze

    def initialize(system_chapter, unmanaged = {})
      @c = system_chapter
      @unmanaged = unmanaged
    end

    def to_s
      sections = [
        *file_header_lines,
        *general_section_lines,
        *security_section_lines,
        *postgresql_section_lines,
        *influxdb_section_lines,
      ]
      sections.push(*unmanaged_section_lines) if unmanaged_env_vars.any?
      sections.join("\n")
    end

    private

    def file_header_lines
      [
        SEPARATOR,
        '# Generated by Helios — DO NOT EDIT MANUALLY!',
        '#',
        '# This file is regenerated from the Helios configuration (SQLite).',
        '# Use the Helios web interface to modify your configuration.',
        SEPARATOR,
        '',
      ]
    end

    def general_section_lines
      [
        '# --- General settings ---',
        *entry('TZ', @c['timezone'],
               'Timezone for all services (IANA format, e.g. Europe/Berlin)'),
        *entry('INSTALLATION_DATE', @c['installation_date'],
               'Date of first solar installation (YYYY-MM-DD) — used for statistics and charts'),
      ]
    end

    def security_section_lines
      [
        '# --- Security ---',
        *entry('ADMIN_PASSWORD', @c['admin_password'],
               'Admin password for the SOLECTRUS web interface'),
        *entry('SECRET_KEY_BASE', @c['secret_key_base'],
               'Rails session secret key — keep this confidential, never share it!'),
      ]
    end

    def postgresql_section_lines
      [
        '# --- PostgreSQL database ---',
        *entry('POSTGRES_PASSWORD', @c['postgres_password'],
               'Database password — auto-generated, do not change after first start'),
        '',
      ]
    end

    def influxdb_section_lines
      [
        '# --- InfluxDB time-series database ---',
        *entry('INFLUX_PASSWORD', @c['influx_password'],
               'Admin password — auto-generated, do not change after first start'),
        *entry('INFLUX_ORG', @c['influx_org'], 'Organization name'),
        *entry('INFLUX_BUCKET', @c['influx_bucket'],
               'Bucket (database) name for time-series data'),
        *entry('INFLUX_TOKEN', @c['influx_token'],
               'API token with full access — auto-generated, do not change after first start'),
      ]
    end

    def unmanaged_section_lines
      [
        '# --- Additional variables (not managed by Helios) ---',
        *unmanaged_env_vars.flat_map { |key, value| ["#{key}=#{value}", ''] },
      ]
    end

    def unmanaged_env_vars
      @unmanaged['env_vars'] || {}
    end

    # Returns three lines: a comment, the key=value assignment, and a blank line.
    def entry(key, value, comment)
      ["# #{comment}", "#{key}=#{value}", '']
    end
  end
end
