class StackBuilder
  class EnvContent
    SEPARATOR = "# #{'=' * 60}".freeze

    def initialize(system_chapter, host_stack_path: nil)
      @system_chapter = system_chapter
      @host_stack_path = host_stack_path
    end

    def to_s
      [
        *file_header_lines,
        *general_section_lines,
        *security_section_lines,
        *postgresql_section_lines,
        *influxdb_section_lines,
        *helios_section_lines,
      ].join("\n")
    end

    private

    attr_reader :system_chapter, :host_stack_path

    def file_header_lines
      [
        SEPARATOR,
        '# Generated by Helios — DO NOT EDIT MANUALLY!',
        '#',
        '# This file is regenerated from the Helios configuration (SQLite).',
        '# Use the Helios web interface to modify your configuration.',
        SEPARATOR,
        '',
      ]
    end

    def general_section_lines
      [
        '# --- General settings ---',
        *entry('TZ', system_chapter['timezone'],
               'Timezone for all services (IANA format, e.g. Europe/Berlin)'),
        *entry('INSTALLATION_DATE', system_chapter['installation_date'],
               'Date of first solar installation (YYYY-MM-DD) — used for statistics and charts'),
      ]
    end

    def security_section_lines
      [
        '# --- Security ---',
        *entry('ADMIN_PASSWORD', system_chapter['admin_password'],
               'Admin password for the SOLECTRUS web interface'),
        *entry('SECRET_KEY_BASE', system_chapter['secret_key_base'],
               'Rails session secret key — keep this confidential, never share it!'),
      ]
    end

    def postgresql_section_lines
      [
        '# --- PostgreSQL database ---',
        *entry('POSTGRES_PASSWORD', system_chapter['postgres_password'],
               'Database password — auto-generated, do not change after first start'),
        '',
      ]
    end

    def influxdb_section_lines
      [
        '# --- InfluxDB time-series database ---',
        *entry('INFLUX_PASSWORD', system_chapter['influx_password'],
               'Admin password — auto-generated, do not change after first start'),
        *entry('INFLUX_ORG', system_chapter['influx_org'], 'Organization name'),
        *entry('INFLUX_BUCKET', system_chapter['influx_bucket'],
               'Bucket (database) name for time-series data'),
        *entry('INFLUX_TOKEN', system_chapter['influx_token'],
               'API token with full access — auto-generated, do not change after first start'),
      ]
    end

    def helios_section_lines
      [
        '# --- Helios ---',
        *entry('HELIOS_HOST_STACK_PATH', host_stack_path,
               'Path on the Docker host where stack files are stored'),
        *entry('HELIOS_SECRET_KEY_BASE', system_chapter['helios_secret_key_base'],
               'Helios session secret key — auto-generated, do not change'),
      ]
    end

    # Returns three lines: a comment, the key=value assignment, and a blank line.
    def entry(key, value, comment)
      ["# #{comment}", "#{key}=#{value}", '']
    end
  end
end
