RSpec.describe StackBuilder do
  let(:configuration) do
    Configuration.current.tap do |config|
      config.installation_date = '2024-01-15'
      config.timezone = 'Europe/Berlin'
      config.save!
    end
  end

  let(:tmp_dir) { Rails.root.join('tmp/test_stack') }
  let(:compose_path) { tmp_dir.join('compose.yaml') }
  let(:env_path) { tmp_dir.join('.env') }

  before do
    FileUtils.mkdir_p(tmp_dir)
    allow(Rails.configuration).to receive(:helios_stack_path).and_return(
      tmp_dir.to_s,
    )
  end

  after { FileUtils.rm_rf(tmp_dir) }

  describe '#write!' do
    before { described_class.new(configuration).write! }

    it 'creates compose.yaml and .env files' do
      expect(File.exist?(compose_path)).to be true
      expect(File.exist?(env_path)).to be true
    end

    it 'creates data directories' do
      expect(Dir.exist?(tmp_dir.join('postgresql'))).to be true
      expect(Dir.exist?(tmp_dir.join('redis'))).to be true
      expect(Dir.exist?(tmp_dir.join('influxdb'))).to be true
    end
  end

  describe '#compose' do
    it 'returns a Compose::File object' do
      builder = described_class.new(configuration)
      expect(builder.compose).to be_a(Compose::File)
    end
  end

  describe '#env' do
    it 'returns an Env::File object' do
      builder = described_class.new(configuration)
      expect(builder.env).to be_a(Env::File)
    end
  end

  describe 'compose file generation' do
    before { described_class.new(configuration).write! }

    it 'sets project name to solectrus' do
      compose = Compose.load
      expect(compose.name).to eq('solectrus')
    end

    it 'includes all required MVP services' do
      compose = Compose.load
      expect(compose.services.names).to contain_exactly(
        'postgresql',
        'redis',
        'influxdb',
        'dashboard',
        'watchtower',
        'helios',
      )
    end

    it 'configures postgresql with healthcheck' do
      compose = Compose.load
      postgresql = compose.services.find('postgresql')

      expect(postgresql.image).to eq('postgres:18-alpine')
      expect(postgresql.healthcheck).to include('test', 'interval')
    end

    it 'configures dashboard with depends_on' do
      compose = Compose.load
      dashboard = compose.services.find('dashboard')

      expect(dashboard.depends_on.keys).to include(
        'postgresql',
        'redis',
        'influxdb',
      )
    end

    it 'preserves existing custom services' do
      compose = Compose.load
      compose.add_service('custom-service', image: 'custom:latest')
      compose.save

      described_class.new(configuration).write!

      compose = Compose.load
      expect(compose.services.exists?('custom-service')).to be true
    end

    it 'includes a generated-by header comment' do
      content = File.read(compose_path)
      expect(content).to include('Generated by Helios')
      expect(content).to include('DO NOT EDIT MANUALLY')
    end
  end

  describe 'env file generation' do
    before { described_class.new(configuration).write! }

    it 'sets user configuration' do
      env = Env.load
      expect(env['INSTALLATION_DATE']).to eq('2024-01-15')
      expect(env['TZ']).to eq('Europe/Berlin')
    end

    it 'generates secrets' do
      env = Env.load
      expect(env['POSTGRES_PASSWORD']).to be_present
      expect(env['INFLUX_PASSWORD']).to be_present
      expect(env['INFLUX_TOKEN']).to be_present
      expect(env['SECRET_KEY_BASE']).to be_present
      expect(env['ADMIN_PASSWORD']).to be_present
    end

    it 'generates secrets with correct lengths' do
      env = Env.load
      expect(env['POSTGRES_PASSWORD'].length).to eq(32)
      expect(env['SECRET_KEY_BASE'].length).to eq(64)
      expect(env['INFLUX_TOKEN'].length).to eq(64)
      expect(env['ADMIN_PASSWORD'].length).to eq(32)
    end

    it 'sets InfluxDB configuration' do
      env = Env.load
      expect(env['INFLUX_ORG']).to eq('solectrus')
      expect(env['INFLUX_BUCKET']).to eq('solectrus')
    end

    it 'includes a generated-by header comment' do
      content = File.read(env_path)
      expect(content).to include('Generated by Helios')
      expect(content).to include('DO NOT EDIT MANUALLY')
    end

    it 'includes inline comments for each variable' do
      content = File.read(env_path)
      expect(content).to include('# Timezone for all services')
      expect(content).to include('# Admin password for the SOLECTRUS')
      expect(content).to include('# Database password')
    end
  end

  describe 'backup behavior' do
    context 'when existing files were not generated by Helios' do
      before do
        File.write(compose_path, "name: solectrus\n")
        File.write(env_path, "TZ=Europe/Berlin\n")
        described_class.new(configuration).write!
      end

      it 'backs up compose.yaml' do
        expect(File.exist?(tmp_dir.join('compose.yaml.bak'))).to be true
      end

      it 'backs up .env' do
        expect(File.exist?(tmp_dir.join('.env.bak'))).to be true
      end

      it 'still writes the new files' do
        expect(File.read(compose_path)).to include('Generated by Helios')
        expect(File.read(env_path)).to include('Generated by Helios')
      end
    end

    context 'when existing files were already generated by Helios' do
      before do
        described_class.new(configuration).write!
        described_class.new(configuration).write!
      end

      it 'does not create a backup for compose.yaml' do
        expect(File.exist?(tmp_dir.join('compose.yaml.bak'))).to be false
      end

      it 'does not create a backup for .env' do
        expect(File.exist?(tmp_dir.join('.env.bak'))).to be false
      end
    end

    context 'when no files exist yet' do
      before { described_class.new(configuration).write! }

      it 'does not create a backup for compose.yaml' do
        expect(File.exist?(tmp_dir.join('compose.yaml.bak'))).to be false
      end

      it 'does not create a backup for .env' do
        expect(File.exist?(tmp_dir.join('.env.bak'))).to be false
      end
    end
  end

  describe 'secret persistence' do
    it 'persists generated secrets to the system chapter in SQLite' do
      described_class.new(configuration).write!

      chapter = configuration.chapter('system')
      expect(chapter['postgres_password']).to be_present
      expect(chapter['secret_key_base']).to be_present
      expect(chapter['admin_password']).to be_present
      expect(chapter['influx_password']).to be_present
      expect(chapter['influx_token']).to be_present
    end

    it 'preserves secrets across multiple writes' do
      described_class.new(configuration).write!
      first_password = configuration.chapter('system')['postgres_password']

      described_class.new(configuration).write!
      second_password = configuration.chapter('system')['postgres_password']

      expect(second_password).to eq(first_password)
    end

    it 'uses existing secrets from SQLite instead of generating new ones' do
      configuration.update_chapter(
        'system',
        configuration.chapter('system').merge('postgres_password' => 'my-existing-secret'),
      )

      described_class.new(configuration).write!

      env = Env.load
      expect(env['POSTGRES_PASSWORD']).to eq('my-existing-secret')
    end
  end
end
