RSpec.describe StackBuilder do
  before { with_config_yaml }

  let(:tmp_dir) { Rails.configuration.helios_stack_path }
  let(:compose_path) { File.join(tmp_dir, 'compose.yaml') }
  let(:env_path) { File.join(tmp_dir, '.env') }

  let(:configuration) do
    config = Configuration.current
    config.update('system', { 'installation_date' => '2024-01-15', 'timezone' => 'Europe/Berlin' })
    config
  end

  describe '#write!' do
    before { described_class.new(configuration).write! }

    it 'creates compose.yaml and .env files' do
      expect(File.exist?(compose_path)).to be true
      expect(File.exist?(env_path)).to be true
    end

    it 'creates data directories' do
      expect(Dir.exist?(File.join(tmp_dir, 'postgresql'))).to be true
      expect(Dir.exist?(File.join(tmp_dir, 'redis'))).to be true
      expect(Dir.exist?(File.join(tmp_dir, 'influxdb'))).to be true
    end
  end

  describe 'compose file generation' do
    before { described_class.new(configuration).write! }

    it 'sets project name to solectrus' do
      compose = Compose.load
      expect(compose.name).to eq('solectrus')
    end

    it 'includes all required MVP services' do
      compose = Compose.load
      expect(compose.services.names).to contain_exactly(
        'postgresql',
        'redis',
        'influxdb',
        'dashboard',
        'watchtower',
        'helios',
      )
    end

    it 'configures postgresql with healthcheck' do
      compose = Compose.load
      postgresql = compose.services.find('postgresql')

      expect(postgresql.image).to eq('postgres:18-alpine')
      expect(postgresql.healthcheck).to include('test', 'interval')
    end

    it 'configures dashboard with depends_on' do
      compose = Compose.load
      dashboard = compose.services.find('dashboard')

      expect(dashboard.depends_on.keys).to include(
        'postgresql',
        'redis',
        'influxdb',
      )
    end

    it 'includes a generated-by header comment' do
      content = File.read(compose_path)
      expect(content).to include('Generated by Helios')
      expect(content).to include('DO NOT EDIT MANUALLY')
    end
  end

  describe 'env file generation' do
    before { described_class.new(configuration).write! }

    it 'sets user configuration' do
      env = Env.load
      expect(env['INSTALLATION_DATE']).to eq('2024-01-15')
      expect(env['TZ']).to eq('Europe/Berlin')
    end

    it 'generates secrets' do
      env = Env.load
      expect(env['POSTGRES_PASSWORD']).to be_present
      expect(env['INFLUX_PASSWORD']).to be_present
      expect(env['INFLUX_TOKEN']).to be_present
      expect(env['SECRET_KEY_BASE']).to be_present
      expect(env['ADMIN_PASSWORD']).to be_present
    end

    it 'generates secrets with correct lengths' do
      env = Env.load
      expect(env['POSTGRES_PASSWORD'].length).to eq(32)
      expect(env['SECRET_KEY_BASE'].length).to eq(128)
      expect(env['INFLUX_TOKEN'].length).to eq(64)
      expect(env['ADMIN_PASSWORD'].length).to eq(32)
    end

    it 'sets InfluxDB configuration' do
      env = Env.load
      expect(env['INFLUX_ORG']).to eq('solectrus')
      expect(env['INFLUX_BUCKET']).to eq('solectrus')
    end

    it 'includes a generated-by header comment' do
      content = File.read(env_path)
      expect(content).to include('Generated by Helios')
      expect(content).to include('DO NOT EDIT MANUALLY')
    end

    it 'includes inline comments for each variable' do
      content = File.read(env_path)
      expect(content).to include('# Timezone for all services')
      expect(content).to include('# Admin password for the SOLECTRUS')
      expect(content).to include('# Database password')
    end
  end

  describe 'backup behavior' do
    context 'when existing files were not generated by Helios' do
      before do
        File.write(compose_path, "name: solectrus\n")
        File.write(env_path, "TZ=Europe/Berlin\n")
        described_class.new(configuration).write!
      end

      it 'backs up compose.yaml' do
        expect(File.exist?(File.join(tmp_dir, 'compose.yaml.bak'))).to be true
      end

      it 'backs up .env' do
        expect(File.exist?(File.join(tmp_dir, '.env.bak'))).to be true
      end

      it 'still writes the new files' do
        expect(File.read(compose_path)).to include('Generated by Helios')
        expect(File.read(env_path)).to include('Generated by Helios')
      end
    end

    context 'when existing files were already generated by Helios' do
      before do
        described_class.new(configuration).write!
        described_class.new(configuration).write!
      end

      it 'does not create a backup for compose.yaml' do
        expect(File.exist?(File.join(tmp_dir, 'compose.yaml.bak'))).to be false
      end

      it 'does not create a backup for .env' do
        expect(File.exist?(File.join(tmp_dir, '.env.bak'))).to be false
      end
    end

    context 'when no files exist yet' do
      before { described_class.new(configuration).write! }

      it 'does not create a backup for compose.yaml' do
        expect(File.exist?(File.join(tmp_dir, 'compose.yaml.bak'))).to be false
      end

      it 'does not create a backup for .env' do
        expect(File.exist?(File.join(tmp_dir, '.env.bak'))).to be false
      end
    end
  end

  describe 'with reverse_proxy configured' do
    before do
      configuration.update('reverse_proxy', {
                             'enabled' => true,
                             'app_domain' => 'solar.example.com',
                           })
      described_class.new(configuration).write!
    end

    it 'includes traefik service in compose.yaml' do
      compose = Compose.load
      expect(compose.services.names).to include('traefik')
    end

    it 'configures traefik with correct image' do
      compose = Compose.load
      traefik = compose.services.find('traefik')
      expect(traefik.image).to eq('traefik:v3')
    end

    it 'removes dashboard ports' do
      compose = Compose.load
      dashboard = compose.services.find('dashboard')
      expect(dashboard.ports).to be_blank
    end

    it 'adds traefik labels to dashboard' do
      compose = Compose.load
      dashboard = compose.services.find('dashboard')
      labels = dashboard.config['labels']
      expect(labels).to include('traefik.enable=true')
      expect(labels).to include(
        'traefik.http.routers.dashboard.rule=Host(`solar.example.com`)',
      )
    end

    it 'sets FORCE_SSL on dashboard' do
      compose = Compose.load
      dashboard = compose.services.find('dashboard')
      expect(dashboard.environment).to include('FORCE_SSL' => 'true')
    end

    it 'includes APP_DOMAIN in .env' do
      env = Env.load
      expect(env['APP_DOMAIN']).to eq('solar.example.com')
    end

    it 'includes LETSENCRYPT_EMAIL in .env' do
      env = Env.load
      expect(env['LETSENCRYPT_EMAIL']).to eq('webmaster@solar.example.com')
    end

    it 'creates traefik data directory' do
      expect(Dir.exist?(File.join(tmp_dir, 'traefik'))).to be true
    end
  end

  describe 'without reverse_proxy configured' do
    before { described_class.new(configuration).write! }

    it 'does not include traefik service' do
      compose = Compose.load
      expect(compose.services.names).not_to include('traefik')
    end

    it 'includes dashboard ports' do
      compose = Compose.load
      dashboard = compose.services.find('dashboard')
      expect(dashboard.ports).to include('3000:3000')
    end

    it 'does not include APP_DOMAIN in .env' do
      content = File.read(env_path)
      expect(content).not_to include('APP_DOMAIN')
    end
  end

  describe 'with backup configured' do
    before do
      configuration.update('backup', {
                             'enabled' => true,
                             'aws_access_key_id' => 'AKIAEXAMPLE',
                             'aws_secret_access_key' => 'secret123',
                             'aws_region' => 'eu-central-1',
                             'aws_bucket' => 'my-bucket',
                           })
      described_class.new(configuration).write!
    end

    it 'includes postgresql-backup service' do
      compose = Compose.load
      expect(compose.services.names).to include('postgresql-backup')
    end

    it 'includes influxdb-backup service' do
      compose = Compose.load
      expect(compose.services.names).to include('influxdb-backup')
    end

    it 'uses unless-stopped restart policies for backup services' do
      compose = Compose.load

      expect(compose.services.find('postgresql-backup').restart).to eq('unless-stopped')
      expect(compose.services.find('influxdb-backup').restart).to eq('unless-stopped')
    end

    it 'configures influxdb-backup with required environment' do
      compose = Compose.load
      influxdb_backup = compose.services.find('influxdb-backup')

      expect(influxdb_backup.environment).to include(
        'INFLUXDB_HOST' => 'influxdb',
        'INFLUXDB_ORG' => '${INFLUX_ORG}',
        'INFLUXDB_TOKEN' => '${INFLUX_TOKEN}',
        'S3_BUCKET' => '${AWS_BUCKET}',
        'S3_PREFIX' => 'influxdb_backup',
        'CRON' => '0 0 * * 0',
      )
      expect(influxdb_backup.environment).not_to include('AWS_REGION' => '${AWS_REGION}')
      expect(influxdb_backup.environment).not_to include('AWS_BUCKET' => '${AWS_BUCKET}')
    end

    it 'includes AWS credentials in .env' do
      env = Env.load
      expect(env['AWS_ACCESS_KEY_ID']).to eq('AKIAEXAMPLE')
      expect(env['AWS_SECRET_ACCESS_KEY']).to eq('secret123')
      expect(env['AWS_REGION']).to eq('eu-central-1')
      expect(env['AWS_BUCKET']).to eq('my-bucket')
    end
  end

  describe 'without backup configured' do
    before { described_class.new(configuration).write! }

    it 'does not include backup services' do
      compose = Compose.load
      expect(compose.services.names).not_to include('postgresql-backup', 'influxdb-backup')
    end

    it 'does not include AWS credentials in .env' do
      content = File.read(env_path)
      expect(content).not_to include('AWS_ACCESS_KEY_ID')
    end
  end

  describe 'secret persistence' do
    it 'persists generated secrets to config.yaml' do
      described_class.new(configuration).write!

      reloaded = Configuration.current
      expect(reloaded.dashboard.admin_password).to be_present
      expect(reloaded.dashboard.secret_key_base).to be_present
      expect(reloaded.postgresql.password).to be_present
      expect(reloaded.influxdb.password).to be_present
      expect(reloaded.influxdb.token).to be_present
    end

    it 'preserves secrets across multiple writes' do
      described_class.new(configuration).write!
      first_password = Configuration.current.postgresql.password

      # Reload configuration from disk for second write
      config2 = Configuration.current
      described_class.new(config2).write!
      second_password = Configuration.current.postgresql.password

      expect(second_password).to eq(first_password)
    end

    it 'uses existing secrets instead of generating new ones' do
      configuration.update(
        'postgresql',
        configuration.postgresql.merge('password' => 'my-existing-secret'),
      )

      described_class.new(Configuration.current).write!

      env = Env.load
      expect(env['POSTGRES_PASSWORD']).to eq('my-existing-secret')
    end
  end
end
