module Export
  module Services
    class Influxdb < Base
      # Container port the InfluxDB HTTP API/UI always listens on.
      CONTAINER_PORT = 8086

      def self.service_name
        'influxdb'
      end

      def self.config_keys
        ['influxdb']
      end

      def self.volume_env_key
        'INFLUX_VOLUME_PATH'
      end

      def self.comment
        'InfluxDB — Time-series database for sensor measurements'
      end

      def self.enabled?(configuration)
        !configuration.collectors_only?
      end

      # True when InfluxDB should be reachable from outside the Docker
      # network. In dashboard_only mode the collectors run on a remote host
      # and write into this stack's InfluxDB across the LAN, so it has to be
      # exposed regardless of the user's preference.
      def self.exposed?(configuration)
        configuration.dashboard_only? || configuration.influxdb.publish_port.present?
      end

      # Host-side port InfluxDB is reachable on — either published directly
      # or served by Traefik's `influxdb` entrypoint.
      def self.host_port(configuration)
        configuration.influxdb.host_port.presence || CONTAINER_PORT
      end

      # True when HELIOS owns the Traefik definition and therefore generates
      # the InfluxDB routing (entrypoint, published port, service labels)
      # itself. An imported custom Traefik — identified by a captured
      # `command` — carries its own routing verbatim instead (ADR-0015).
      def self.traefik_managed_routing?(configuration)
        exposed?(configuration) &&
          Traefik.enabled?(configuration) &&
          configuration.reverse_proxy.command.blank?
      end

      def data_directories
        managed_data_directory
      end

      def to_h
        config = {
          image: configuration.influxdb.image,
          environment: influxdb_environment,
          volumes: [bind_mount('/var/lib/influxdb2')],
          restart: 'unless-stopped',
          healthcheck: healthcheck('CMD', 'influx', 'ping'),
        }

        if traefik_managed_routing?
          # HELIOS owns Traefik: route InfluxDB through it (HTTPS, same
          # domain) instead of publishing a host port directly.
          config[:labels] = traefik_labels
        elsif exposed? && !traefik_routes_influxdb?
          # Publish a host port directly — either Traefik is off, or an
          # imported Traefik has no `influxdb` entrypoint to route through.
          config[:ports] = ["#{host_port}:#{CONTAINER_PORT}"]
        end
        # Remaining case: imported Traefik already routes InfluxDB via its
        # own `influxdb` entrypoint — its labels come in via service_overrides,
        # and no direct port is published (avoids clashing with Traefik).

        config
      end

      private

      def exposed?
        self.class.exposed?(configuration)
      end

      def host_port
        self.class.host_port(configuration)
      end

      def traefik_managed_routing?
        self.class.traefik_managed_routing?(configuration)
      end

      # Whether the active Traefik exposes InfluxDB through a dedicated
      # `influxdb` entrypoint — generated by HELIOS, or declared by an
      # imported custom Traefik command. When it does, InfluxDB must not
      # also publish a host port (Traefik owns it); when it doesn't, an
      # exposed InfluxDB falls back to a direct port mapping.
      def traefik_routes_influxdb?
        return false unless Traefik.enabled?(configuration)

        command = configuration.reverse_proxy.command
        if command.blank?
          exposed? # HELIOS adds the entrypoint itself when InfluxDB is exposed
        else
          command.any? { |arg| arg.to_s.start_with?('--entrypoints.influxdb.') }
        end
      end

      def traefik_labels
        domain = configuration.reverse_proxy.app_domain
        [
          'traefik.enable=true',
          "traefik.http.routers.influxdb.rule=Host(`#{domain}`)",
          'traefik.http.routers.influxdb.entrypoints=influxdb',
          'traefik.http.routers.influxdb.tls.certresolver=letsencrypt',
          "traefik.http.services.influxdb.loadbalancer.server.port=#{CONTAINER_PORT}",
        ]
      end

      def influxdb_environment
        env = [
          'TZ',
          'DOCKER_INFLUXDB_INIT_MODE=setup',
          'DOCKER_INFLUXDB_INIT_USERNAME=admin',
          'DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUX_PASSWORD}',
          'DOCKER_INFLUXDB_INIT_ORG=${INFLUX_ORG}',
          'DOCKER_INFLUXDB_INIT_BUCKET=${INFLUX_BUCKET}',
          'DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUX_ADMIN_TOKEN}',
        ]
        env << 'INFLUXD_USE_HASHED_TOKENS' if configuration.influxdb.use_hashed_tokens.present?
        env
      end
    end
  end
end
