class SensorRegistry
  SENSORS = {
    'INVERTER_POWER' => { unit: 'W' },
    'INVERTER_POWER_1' => { unit: 'W' },
    'INVERTER_POWER_2' => { unit: 'W' },
    'INVERTER_POWER_3' => { unit: 'W' },
    'INVERTER_POWER_4' => { unit: 'W' },
    'INVERTER_POWER_5' => { unit: 'W' },
    'INVERTER_POWER_FORECAST' => { unit: 'W' },
    'INVERTER_POWER_FORECAST_CLEARSKY' => { unit: 'W' },
    'HOUSE_POWER' => { unit: 'W' },
    'GRID_IMPORT_POWER' => { unit: 'W' },
    'GRID_EXPORT_POWER' => { unit: 'W' },
    'GRID_EXPORT_LIMIT' => { unit: '%' },
    'BATTERY_CHARGING_POWER' => { unit: 'W' },
    'BATTERY_DISCHARGING_POWER' => { unit: 'W' },
    'BATTERY_SOC' => { unit: '%' },
    'WALLBOX_POWER' => { unit: 'W' },
    'WALLBOX_CAR_CONNECTED' => { unit: '' },
    'CAR_BATTERY_SOC' => { unit: '%' },
    'CASE_TEMP' => { unit: '°C' },
    'OUTDOOR_TEMP' => { unit: '°C' },
    'OUTDOOR_TEMP_FORECAST' => { unit: '°C' },
    'SYSTEM_STATUS' => { unit: '' },
    'SYSTEM_STATUS_OK' => { unit: '' },
    'HEATPUMP_POWER' => { unit: 'W' },
    'HEATPUMP_HEATING_POWER' => { unit: 'W' },
    'HEATPUMP_TANK_TEMP' => { unit: '°C' },
    'HEATPUMP_STATUS' => { unit: '' },
    'CUSTOM_POWER_01' => { unit: 'W' },
    'CUSTOM_POWER_02' => { unit: 'W' },
    'CUSTOM_POWER_03' => { unit: 'W' },
    'CUSTOM_POWER_04' => { unit: 'W' },
    'CUSTOM_POWER_05' => { unit: 'W' },
    'CUSTOM_POWER_06' => { unit: 'W' },
    'CUSTOM_POWER_07' => { unit: 'W' },
    'CUSTOM_POWER_08' => { unit: 'W' },
    'CUSTOM_POWER_09' => { unit: 'W' },
    'CUSTOM_POWER_10' => { unit: 'W' },
    'CUSTOM_POWER_11' => { unit: 'W' },
    'CUSTOM_POWER_12' => { unit: 'W' },
    'CUSTOM_POWER_13' => { unit: 'W' },
    'CUSTOM_POWER_14' => { unit: 'W' },
    'CUSTOM_POWER_15' => { unit: 'W' },
    'CUSTOM_POWER_16' => { unit: 'W' },
    'CUSTOM_POWER_17' => { unit: 'W' },
    'CUSTOM_POWER_18' => { unit: 'W' },
    'CUSTOM_POWER_19' => { unit: 'W' },
    'CUSTOM_POWER_20' => { unit: 'W' },
  }.freeze

  def self.unit_for(sensor_name)
    SENSORS.dig(sensor_name, :unit) || ''
  end
end
