class SensorRegistry
  SENSORS = {
    'inverter_power' => { unit: 'W' },
    'inverter_power_1' => { unit: 'W' },
    'inverter_power_2' => { unit: 'W' },
    'inverter_power_3' => { unit: 'W' },
    'inverter_power_4' => { unit: 'W' },
    'inverter_power_5' => { unit: 'W' },
    'inverter_power_forecast' => { unit: 'W' },
    'inverter_power_forecast_clearsky' => { unit: 'W' },
    'house_power' => { unit: 'W' },
    'grid_import_power' => { unit: 'W' },
    'grid_export_power' => { unit: 'W' },
    'grid_export_limit' => { unit: '%' },
    'battery_charging_power' => { unit: 'W' },
    'battery_discharging_power' => { unit: 'W' },
    'battery_soc' => { unit: '%' },
    'wallbox_power' => { unit: 'W' },
    'wallbox_car_connected' => { unit: '' },
    'car_battery_soc' => { unit: '%' },
    'case_temp' => { unit: '°C' },
    'outdoor_temp' => { unit: '°C' },
    'outdoor_temp_forecast' => { unit: '°C' },
    'system_status' => { unit: '' },
    'system_status_ok' => { unit: '' },
    'heatpump_power' => { unit: 'W' },
    'heatpump_heating_power' => { unit: 'W' },
    'heatpump_tank_temp' => { unit: '°C' },
    'heatpump_status' => { unit: '' },
    'custom_power_01' => { unit: 'W' },
    'custom_power_02' => { unit: 'W' },
    'custom_power_03' => { unit: 'W' },
    'custom_power_04' => { unit: 'W' },
    'custom_power_05' => { unit: 'W' },
    'custom_power_06' => { unit: 'W' },
    'custom_power_07' => { unit: 'W' },
    'custom_power_08' => { unit: 'W' },
    'custom_power_09' => { unit: 'W' },
    'custom_power_10' => { unit: 'W' },
    'custom_power_11' => { unit: 'W' },
    'custom_power_12' => { unit: 'W' },
    'custom_power_13' => { unit: 'W' },
    'custom_power_14' => { unit: 'W' },
    'custom_power_15' => { unit: 'W' },
    'custom_power_16' => { unit: 'W' },
    'custom_power_17' => { unit: 'W' },
    'custom_power_18' => { unit: 'W' },
    'custom_power_19' => { unit: 'W' },
    'custom_power_20' => { unit: 'W' },
  }.freeze

  def self.unit_for(sensor_name)
    SENSORS.dig(sensor_name, :unit) || ''
  end
end
